### PR TITLE
Enhance getting avatar images and add `get_avatar_data` filter

### LINKED ISSUE #5771: Also add `get_avatar_data` filter for Avatar fields.
**Describe the bug**

https://wordpress.org/support/topic/profile-avatar-not-working/

### PR DESCRIPTION
**Pull request by JoryHogeveen**
## Description

Fixes #5771 

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.
- [ ] My code includes PHP Unit Tests (if applicable)

### CODE REVIEW

File: classes/fields/avatar.php [hunk 1]
```diff
@@ -88,30 +88,151 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
 
+		return $avatar;
+	}
+
+	/**
+	 * Take over the avatar data served from WordPress
+	 *
+	 * @since 2.7.22
+	 *
+	 * @param mixed $id_or_email The Gravatar to retrieve. Accepts a user ID, Gravatar MD5 hash,
```
Comment (tr1b0t) [inline classes/fields/avatar.php:131]: :no_entry_sign: Doc comment for parameter $id_or_email does not match actual variable name $args

<sub>hash: 8eb400ef4a2b492afce046d1da82aab7</sub>

File: classes/fields/avatar.php [hunk 2]
```diff
@@ -88,30 +88,151 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
+	 *                           user email, WP_User object, WP_Post object, or WP_Comment object.
+	 * @param array $args {
```
Comment (tr1b0t) [inline classes/fields/avatar.php:133]: :no_entry_sign: Doc comment for parameter $args does not match actual variable name $id_or_email

<sub>hash: 2966668ad1b8a89012bf5779b4d00257</sub>

File: classes/fields/avatar.php [hunk 3]
```diff
@@ -88,30 +88,151 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
+			} else {
+
+				$user_avatar_id = $this->get_avatar_id( $user_id );
+
+				if ( ! empty( $user_avatar_id ) ) {
+
+					$user_avatar_url = pods_image_url( $user_avatar_id, array( $args['width'], $args['height'] ), 0 );
+
+					if ( ! empty( $user_avatar_url ) ) {
+						pods_cache_set( $user_id . '-' . $size . '-url', $user_avatar_url, 'pods_avatars' );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:200]: Let's not set a forever limit here

File: classes/fields/avatar.php [hunk 4]
```diff
@@ -132,32 +253,45 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
 				if ( ! empty( $avatar_field ) ) {
-					$user_avatar = get_user_meta( $user_id, $avatar_field . '.ID', true );
+					$avatar_id = get_user_meta( $user_id, $avatar_field . '.ID', true );
 
-					if ( ! empty( $user_avatar ) ) {
-						$attributes = array(
-							'alt'   => '',
-							'class' => 'avatar avatar-' . $size . ' photo',
-						);
+					pods_cache_set( $user_id . '-id', $avatar_id, 'pods_avatars' );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:258]: Lets set an expiration on this

File: classes/fields/avatar.php [hunk 5]
```diff
@@ -88,30 +88,151 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
+					if ( ! empty( $alt ) ) {
+						$attributes['alt'] = $alt;
+					}
+
+					$user_avatar = pods_image( $user_avatar, array( $size, $size ), 0, $attributes );
+
+					if ( ! empty( $user_avatar ) ) {
+						$avatar = $user_avatar;
+
+						pods_cache_set( $user_id . '-' . $size, $avatar, 'pods_avatars' );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:117]: Lets set an expiration on this

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 
About the cache part. I only added this because the original `get_avatar()` method used it.
However, now that I think of it, how is this cache being purged at the moment? To prevent unnecessary support requests all cache should be removed one the avatar is updated or removed.

File: classes/fields/avatar.php [hunk 6]
```diff
@@ -132,32 +254,72 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
+	 *
+	 * @return bool
+	 */
+	public function allow_avatar_overwrite() {
+
+		// Don't replace for the Avatars section of the Discussion settings page.
+		if ( is_admin() && ! doing_action( 'admin_bar_menu' ) ) {
+			$current_screen = get_current_screen();
+
+			$screens = array(
```
Comment (JoryHogeveen) [inline classes/fields/avatar.php:311]: @sc0ttkclark Do you agree on this part?

– User edit page (since this is the actual Gravatar)
– Profile edit page (since this is the actual Gravatar)
– Discussion page (user avatar preview options).

For these locations the Gravatar will not be overwritten since that is WordPress core.

File: classes/fields/avatar.php (hunk 3 above)
Comment (JoryHogeveen) [reply classes/fields/avatar.php:201]: How long?

File: classes/fields/avatar.php (hunk 4 above)
Comment (JoryHogeveen) [reply classes/fields/avatar.php:259]: How long?

File: classes/fields/avatar.php (hunk 3 above)
Comment (sc0ttkclark) [reply classes/fields/avatar.php:201]: 1 week seems like it'd be OK

File: classes/fields/avatar.php (hunk 5 above)
Comment (sc0ttkclark) [reply classes/fields/avatar.php:112]: 1 week seems like it'd be OK

File: classes/fields/avatar.php (hunk 4 above)
Comment (sc0ttkclark) [reply classes/fields/avatar.php:259]: 1 week seems like it'd be OK

File: classes/fields/avatar.php (hunk 6 above)
Comment (sc0ttkclark) [reply classes/fields/avatar.php:311]: Sounds good to me, the edit page could be optional though, maybe someone might want to know what that avatar would be (if using the avatar field)

File: classes/PodsInit.php [hunk 7]
```diff
@@ -469,6 +469,10 @@ public function core() {
 		if ( method_exists( $avatar, 'get_avatar' ) ) {
 			add_filter( 'get_avatar', array( $avatar, 'get_avatar' ), 10, 4 );
 		}
+
+		if ( method_exists( $avatar, 'get_avatar_data' ) ) {
+			add_filter( 'get_avatar_data', array( $avatar, 'get_avatar_data' ), 10, 2 );
```
Comment (tr1b0t) [inline classes/PodsInit.php:474]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: bdb199c013885b1de31d8c7b30e432b6</sub>

File: classes/fields/avatar.php [hunk 8]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+			$avatar_cached = pods_cache_get( $user_id . '-' . $size, 'pods_avatars' );
+
+			if ( ! empty( $avatar_cached ) ) {
+				$avatar = $avatar_cached;
+			} else {
+
+				$user_avatar = $this->get_avatar_id( $user_id );
+
+				if ( ! empty( $user_avatar ) ) {
+					$attributes = array(
```
Comment (tr1b0t) [inline classes/fields/avatar.php:98]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: b7e81f8103e53e39d008e5ba911cc27b</sub>

File: classes/fields/avatar.php [hunk 9]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+						'class' => 'avatar avatar-' . $size . ' photo',
+					);
 
-			if ( null !== $current_screen && 'options-discussion' === $current_screen->id && 32 === $size ) {
-				return $avatar;
+					if ( ! empty( $alt ) ) {
+						$attributes['alt'] = $alt;
+					}
+
+					$user_avatar = pods_image( $user_avatar, array( $size, $size ), 0, $attributes );
```
Comment (tr1b0t) [inline classes/fields/avatar.php:107]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 7cba6a541a8ac6629b70144af67214fd</sub>

File: classes/fields/avatar.php [hunk 10]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+			return $args;
+		}
 
-			if ( ! empty( $_user ) ) {
-				$user_id = (int) $_user->ID;
+		$return_args = $args;
+
+		$args = wp_parse_args(
+			$args,
+			array(
```
Comment (tr1b0t) [inline classes/fields/avatar.php:166]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: be84cfc77ca9c6a3452e2ab603bb59b0</sub>

File: classes/fields/avatar.php [hunk 11]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+
+			if ( ! empty( $avatar_cached ) ) {
+				$user_avatar_url = $avatar_cached;
+			} else {
+
+				$user_avatar_id = $this->get_avatar_id( $user_id );
+
+				if ( ! empty( $user_avatar_id ) ) {
+
+					$user_avatar_url = pods_image_url( $user_avatar_id, array( $args['width'], $args['height'] ), 0 );
```
Comment (tr1b0t) [inline classes/fields/avatar.php:198]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 7b4cf79f730ebb8c2b39e1b5bcbbe311</sub>

File: classes/fields/avatar.php [hunk 12]
```diff
@@ -132,33 +254,71 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
+	 * @return bool
+	 */
+	public function allow_avatar_overwrite() {
 
-		return $avatar;
+		// Don't replace for the Avatars section of the Discussion settings page.
+		if ( is_admin() && ! doing_action( 'admin_bar_menu' ) ) {
+			$current_screen = get_current_screen();
+
+			$screens = array(
```
Comment (tr1b0t) [inline classes/fields/avatar.php:310]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 1900f0d858bb182b37a120ecf0c7c42f</sub>

**Review by tr1b0t — COMMENTED** [review]
:no_entry_sign: 6 error(s)

File: classes/fields/avatar.php (hunk 6 above)
Comment (JoryHogeveen) [reply classes/fields/avatar.php:310]: The Pods field would still be there so that is still available in those screens.
IMO that is sufficient :)

**Comment by JoryHogeveen** [comment]
> Needs a couple of changes here

Done!

File: classes/fields/avatar.php [hunk 13]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+	public function get_avatar_id( $id_or_email ) {
+		$user_id = $this->get_avatar_user_id( $id_or_email );
+
 		// Include PodsMeta if not already included.
 		pods_meta();
+		$avatar_id = 0;
 
 		if ( 0 < $user_id && ! empty( PodsMeta::$user ) ) {
-			$avatar_cached = pods_cache_get( $user_id . '-' . $size, 'pods_avatars' );
+			$avatar_cached = pods_cache_get( $user_id . '-id', 'pods_avatars' );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:233]:
```suggestion
			$avatar_cached = pods_cache_get( $user_id . '-id', 'pods_avatar_ids' );
```

File: classes/fields/avatar.php [hunk 14]
```diff
@@ -132,33 +254,71 @@ public function get_avatar( $avatar, $id_or_email, $size, $default = '', $alt =
...
-					$user_meta   = get_user_meta( $user_id );
-					$user_avatar = ! empty( $user_meta[ $avatar_field ][0] ) ? $user_meta[ $avatar_field ][0] : false;
+					$avatar_id = get_user_meta( $user_id, $avatar_field . '.ID', true );
 
-					if ( ! empty( $user_avatar ) ) {
-						$attributes = array(
-							'alt'   => '',
-							'class' => 'avatar avatar-' . $size . ' photo',
-						);
+					pods_cache_set( $user_id . '-id', $avatar_id, 'pods_avatars', WEEK_IN_SECONDS );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:259]:
```suggestion
					pods_cache_set( $user_id . '-id', $avatar_id, 'pods_avatar_ids', WEEK_IN_SECONDS );
```

File: classes/fields/avatar.php [hunk 15]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+		$size = $args['size'];
+		if ( $args['width'] !== $args['height'] ) {
+			$size = $args['width'] . 'x' . $args['height'];
+		}
+
+		$user_id = $this->get_avatar_user_id( $id_or_email );
+
+		if ( 0 < $user_id && ! empty( PodsMeta::$user ) ) {
+			$user_avatar_url = null;
+			$avatar_cached   = pods_cache_get( $user_id . '-' . $size . '-url', 'pods_avatars' );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:188]:
```suggestion
			$avatar_cached   = pods_cache_get( $user_id . '-' . $size . '-url', 'pods_avatar_urls' );
```

File: classes/fields/avatar.php [hunk 16]
```diff
@@ -79,39 +79,161 @@ public function input( $name, $value = null, $options = null, $pod = null, $id =
...
+			} else {
+
+				$user_avatar_id = $this->get_avatar_id( $user_id );
+
+				if ( ! empty( $user_avatar_id ) ) {
+
+					$user_avatar_url = pods_image_url( $user_avatar_id, array( $args['width'], $args['height'] ), 0 );
+
+					if ( ! empty( $user_avatar_url ) ) {
+						pods_cache_set( $user_id . '-' . $size . '-url', $user_avatar_url, 'pods_avatars', WEEK_IN_SECONDS );
```
Comment (sc0ttkclark) [inline classes/fields/avatar.php:201]:
```suggestion
						pods_cache_set( $user_id . '-' . $size, $user_avatar_url, 'pods_avatar_urls', WEEK_IN_SECONDS );
```

**Review by sc0ttkclark — APPROVED** [review]
