### PR TITLE
REST API Write access - Fix invalid default value

### LINKED ISSUE #7327: Custom fields not updating via REST API
> Seems like it still doesn't work. Meta data fields i POST through the WP API remain empty. Whether i set "Allow All Fields To Be Updated" or allow one by one on field level. Should i raise a new issue for this?

_Originally posted by @kilianso in https://github.com/pods-framework/pods/issues/7318#issuecomment-2232900895_

### PR DESCRIPTION
**Pull request by JoryHogeveen**
## Description

De default value for the `write_all` option of a Pod was set to the Pod name. This results in incorrect parsing of a boolean in `PodsRESTFields::field_allowed_to_extend()` in `write` mode.

@sc0ttkclark See testing instructions. I'm not sure how you would like to implement something that will repair old Pods. You could check for `! empty()` instead of using `filter_var()` but that might not be desirable. 

## Related GitHub issue(s)

Fixes #7327

## Testing instructions

1. Create a Pod without this patch and enable write mode.
2. Go to `PodsRESTFields::field_allowed_to_extend()` and dump `$all_fields_can_use_mode`. It will return false, allways.
3. Verify with `$pod->get_arg( $pod_mode_arg, 'value_not_set' )` and see it returns the Pod name instead of a 1 or 0.
4. Apply this patch
5. Disable REST write access and save Pod (important, otherwise it won't reset the value)
6. Re-enable REST Write access and save Pod.
7. Redo 1, 2 and 3 and you'll see it returns the correct values now.

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).

### CODE REVIEW

File: classes/PodsAdmin.php [hunk 1]
```diff
@@ -4418,7 +4418,7 @@ public function add_rest_settings_tab_fields( $options, $pod ) {
 				'label'             => __( 'Allow All Fields To Be Updated', 'pods' ),
 				'help'              => __( 'Allow all fields to be updated via the REST API. If unchecked fields must be enabled on a field by field basis.', 'pods' ),
 				'type'              => 'boolean',
-				'default'           => pods_v( 'name', $pod ),
+				'default'           => '',
```
Comment (PodsBot) [inline classes/PodsAdmin.php:4421]: **[phpcs]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned`<br>Array double arrow not aligned correctly; expected 4 space(s) between "'default'" and double arrow, but found 11.

File: classes/PodsAdmin.php [hunk 2]
```diff
@@ -4415,11 +4415,11 @@ public function add_rest_settings_tab_fields( $options, $pod ) {
...
-				'label'             => __( 'Allow All Fields To Be Updated', 'pods' ),
-				'help'              => __( 'Allow all fields to be updated via the REST API. If unchecked fields must be enabled on a field by field basis.', 'pods' ),
-				'type'              => 'boolean',
-				'default'           => pods_v( 'name', $pod ),
-				'depends-on'        => [ 'rest_enable' => true, 'read_all' => true ],
+				'label'      => __( 'Allow All Fields To Be Updated', 'pods' ),
+				'help'       => __( 'Allow all fields to be updated via the REST API. If unchecked fields must be enabled on a field by field basis.', 'pods' ),
+				'type'       => 'boolean',
+				'default'    => '',
+				'depends-on' => [ 'rest_enable' => true, 'read_all' => true ],
```
Comment (PodsBot) [inline classes/PodsAdmin.php:4422]: **[phpcs]** <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>`WordPress.Arrays.ArrayDeclarationSpacing.AssociativeArrayFound`<br>When a multi-item array uses associative keys, each value should start on a new line.

Comment (JoryHogeveen) [reply classes/PodsAdmin.php:4422]: @sc0ttkclark This is throughout the whole array, want me to fix or leave as is?

Comment (sc0ttkclark) [reply classes/PodsAdmin.php:4422]: The phpcs stuff is just optional to fix. Autoformat can help but it's file by file as we're able to.

**Review by sc0ttkclark — APPROVED** [review]

**Review by sc0ttkclark — APPROVED** [review]

**Comment by sc0ttkclark** [comment]
Added backcompat handling but did not include a DB migration.
