### PR TITLE
Force node v7 for precise/PHP 5.3 tests

### LINKED ISSUE #4547: Travis tests failing on 5.3/precise with latest node
PR incoming to test fix

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #4547

### CODE REVIEW

**Comment by pglewis** [comment]
Fixes #4547

File: bin/init.sh [hunk 1]
```diff
@@ -1,34 +1,34 @@
 #!/usr/bin/env bash
 
 
-echo "Removeding xdebug from PHP"
+echo "Removeing xdebug from PHP"
```
Comment (jamesgol) [inline bin/init.sh]: Remove, Removed, Removing
