### PR TITLE
Fixes for WP 5.3

### LINKED ISSUE #5499: Update CSS for WP 5.3
WordPress 5.3 introduces changes in UI and Pods will need to adjust the CSS for this.

**Todo:**
- [x] Fix boolean field width (checkbox)
- [x] Table border colors
- [x] Modal window
- [ ] ...

### LINKED ISSUE #5500: Fix DFV modal issue
WordPress 5.3 seems to break the DFV modal popup.
- [x] The adminbar and admin menu shouldn't be visible. (Fixed in #5501)
- [ ] Also there is an error:

```
Uncaught TypeError: Cannot read property 'isCurrentPostPublished' of null
    at i (pods-dfv.min.js:1)
    at HTMLDocument.<anonymous> (pods-dfv.min.js:1)
```

- [ ] Backbone is updated to 1.4.0 (not sure if Pods is affected by this)
https://github.com/pods-framework/pods/blob/2.x/ui/js/pods-dfv/_src/file-upload/file-upload.js#L60
More info about the backbone update here: https://make.wordpress.org/core/2019/10/10/wordpress-5-3-backbone-upgrade-guide/

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Related #5500 
Fixes #5499

## Checklist:
- [ ] My code is tested.
- [ ] My code follows the WordPress code style.
- [ ] My code follows has proper inline documentation.

### CODE REVIEW

File: ui/js/pods-dfv/_src/core/iframe-frame.js [hunk 1]
```diff
@@ -28,9 +28,6 @@ export const IframeFrame = wp.media.view.Frame.extend( {
 
 		this.on( 'title:create:default', this.createTitle, this );
 		this.title.mode( 'default' );
-		this.on( 'title:render', function ( view ) {
```
Comment (sc0ttkclark) [inline ui/js/pods-dfv/_src/core/iframe-frame.js]: @JoryHogeveen Is this only a WP 5.3 thing? Does it work fine for our min WP version (4.5 right now, but it's upped for 2.8)?

Comment (JoryHogeveen) [reply ui/js/pods-dfv/_src/core/iframe-frame.js]: Pre WP 5.3 it's not visible either (The icon is made invisible in core CSS). I'm guessing it's left-over code within WP.

**Comment by JoryHogeveen** [comment]
It might change the display for Pre WP 5.3 slightly but there are no big changes. Only adjusting colors to match 5.3 and a fix for Gutenberg.
