### PR TITLE
Formerly `extract`ed variables were in `$args`, not `$instance`

### LINKED ISSUE #4891: Pods Widgets breakage in 2.7.2
## Issue Overview

After updating Pods View Widget TITLE is missing styling (guess it's issue with removing before title and after title made in PodsWidgetView.php?)
 I've reverted update via GIT and will wait for fixing this bug until I update it.
Thank you,
Zeljko

## Expected Behavior
Normally, widget titles are surrounded by `<h2 class="widget-title">` and `</h2>`

## Current Behavior
Widgets are just putting plain-text above the Widget content.

## Possible Solution
No workaround. This is broken.

## Steps to Reproduce (for bugs)
1. Add any Pods Widget to your site. 

## WordPress Environment
<details>
```
Debug Information
WordPress Version: 4.9.5

PHP Version: 5.6.36

MySQL Version: 5.6.39

Server Software: Apache

Your User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36

Session Save Path: /tmp

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: Yes
Redis: Yes
WPDB Prefix: wp_6kilo6veckor_se_

WP Multisite Mode: No

WP Memory Limit: 40M

Pods Network-Wide Activated: No

Pods Install Location: /home2/ulrikada/public_html/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Ulrika Davidsson 2016

Currently Active Plugins:

Admin Columns: 3.1.10
Akismet Anti-Spam: 4.0.3
Awebsome! Browser Selector: 2.2
Awebsome Browser Selector for CACHING: 1.0.2
CMS Tree Page View: 1.5
Comet Cache: 170220
Cookie Law Info: 1.5.3
Duplicate Post: 3.2.2
Email Address Encoder: 1.0.7
Email JavaScript Cloaker: 1.03
Exclude Pages from Navigation: 1.92
Facebook Like Box: 2.9
Feedzy RSS Feeds Lite: 3.2.10
Genesis 404: 1.5.0
Genesis Featured Grid: 1.0
Genesis Featured Widget Amplified: 0.9.2
Genesis Layout Extras: 2.0.0
Genesis Responsive Slider: 0.9.6
Genesis Simple Edits: 2.2.1
Genesis Simple Hooks: 2.2.1
Get a Newsletter: 2.0.7
Google Analytics Dashboard for WP (GADWP): 5.3.2
Google Captcha (reCAPTCHA) by BestWebSoft: 1.36
Gravity Forms: 2.0.7
HungryFEED: 1.6.3
Image Widget: 4.4.7
Imsanity: 2.3.10
ManageWP - Worker: 4.5.0
P3 (Plugin Performance Profiler): 1.5.3.9
Page Links To: 2.9.10
PHP Code Widget: 2.3
Plugin Vulnerabilities: 2.0.64
Pods - Custom Content Types and Fields: 2.7.1
Post Types Order: 1.9.3.6
Power Code Editor: 1.2.1
Redirection: 3.2
Regenerate Thumbnails: 3.0.2
Responsive Menu: 3.1.14
Search Everything: 8.1.9
ShareThis: 7.8
Shortcode Exec PHP: 1.52
SI Captcha Anti-Spam: 3.0.3
Simple Custom CSS: 4.0.1
SSL Insecure Content Fixer: 2.5.0
TinyMCE Advanced: 4.6.7
TinyMCE and TinyMCE Advanced Professsional Formats and Styles: 1.1.2
Updater by BestWebSoft: 1.38
UpdraftPlus - Backup/Restore: 1.14.7
User Switching: 1.3.0
Velvet Blues Update URLs: 3.2.8
Widget Logic: 5.9.0
Widgets On Pages: 1.4.0
WordPress Importer: 0.6.4
WP-Polls: 2.73.8
WP Encrypt: 1.0.0-beta.8
WP Force SSL: 1.3
WP Maintenance Mode: 2.1.2
WP Responsive Recent Post Slider Pro: 1.3.1
WP Security Audit Log: 3.1.7
Yoast SEO: 7.4.2
```
</details>

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #4891

### CODE REVIEW

File: classes/widgets/PodsWidgetForm.php [hunk 1]
```diff
@@ -23,13 +23,13 @@ public function __construct( $id_base = '', $name = '', $widget_options = array(
 	public function widget( $args, $instance ) {
 
 		// Setup basic widget parameters.
-		$before_widget  = pods_v( 'before_widget', $instance );
-		$after_widget   = pods_v( 'after_widget', $instance );
-		$before_title   = pods_v( 'before_title', $instance );
+		$before_widget  = pods_v( 'before_widget', $args );
+		$after_widget   = pods_v( 'after_widget', $args );
+		$before_title   = pods_v( 'before_title', $args );
 		$title          = apply_filters( 'widget_title', pods_v( 'title', $instance ) );
```
Comment (sc0ttkclark) [inline classes/widgets/PodsWidgetForm.php]: `$args` here too?

File: classes/widgets/PodsWidgetField.php [hunk 2]
```diff
@@ -23,13 +23,13 @@ public function __construct( $id_base = '', $name = '', $widget_options = array(
 	public function widget( $args, $instance ) {
 
 		// Setup basic widget parameters.
-		$before_widget  = pods_v( 'before_widget', $instance );
-		$after_widget   = pods_v( 'after_widget', $instance );
-		$before_title   = pods_v( 'before_title', $instance );
+		$before_widget  = pods_v( 'before_widget', $args );
+		$after_widget   = pods_v( 'after_widget', $args );
+		$before_title   = pods_v( 'before_title', $args );
 		$title          = apply_filters( 'widget_title', pods_v( 'title', $instance ) );
```
Comment (sc0ttkclark) [inline classes/widgets/PodsWidgetField.php]: `$args` here too?

File: classes/widgets/PodsWidgetList.php [hunk 3]
```diff
@@ -23,13 +23,13 @@ public function __construct( $id_base = '', $name = '', $widget_options = array(
 	public function widget( $args, $instance ) {
 
 		// Setup basic widget parameters.
-		$before_widget  = pods_v( 'before_widget', $instance );
-		$after_widget   = pods_v( 'after_widget', $instance );
-		$before_title   = pods_v( 'before_title', $instance );
+		$before_widget  = pods_v( 'before_widget', $args );
+		$after_widget   = pods_v( 'after_widget', $args );
+		$before_title   = pods_v( 'before_title', $args );
 		$title          = apply_filters( 'widget_title', pods_v( 'title', $instance ) );
```
Comment (sc0ttkclark) [inline classes/widgets/PodsWidgetList.php]: `$args` here too?

File: classes/widgets/PodsWidgetSingle.php [hunk 4]
```diff
@@ -22,13 +22,13 @@ public function __construct( $id_base = '', $name = '', $widget_options = array(
 	public function widget( $args, $instance ) {
 
 		// Setup basic widget parameters.
-		$before_widget  = pods_v( 'before_widget', $instance );
-		$after_widget   = pods_v( 'after_widget', $instance );
-		$before_title   = pods_v( 'before_title', $instance );
+		$before_widget  = pods_v( 'before_widget', $args );
+		$after_widget   = pods_v( 'after_widget', $args );
+		$before_title   = pods_v( 'before_title', $args );
 		$title          = apply_filters( 'widget_title', pods_v( 'title', $instance ) );
```
Comment (sc0ttkclark) [inline classes/widgets/PodsWidgetSingle.php]: etc

File: classes/widgets/PodsWidgetView.php [hunk 5]
```diff
@@ -23,13 +23,13 @@ public function __construct( $id_base = '', $name = '', $widget_options = array(
 	public function widget( $args, $instance ) {
 
 		// Setup basic widget parameters.
-		$before_widget  = pods_v( 'before_widget', $instance );
-		$after_widget   = pods_v( 'after_widget', $instance );
-		$before_title   = pods_v( 'before_title', $instance );
+		$before_widget  = pods_v( 'before_widget', $args );
+		$after_widget   = pods_v( 'after_widget', $args );
+		$before_title   = pods_v( 'before_title', $args );
 		$title          = apply_filters( 'widget_title', pods_v( 'title', $instance ) );
```
Comment (sc0ttkclark) [inline classes/widgets/PodsWidgetView.php]: i'm hungry
