### PR TITLE
Fixes issue with List Select value list erroring when options are not found

### LINKED ISSUE #6532: User Relationships : Limit by roles > Field error
### Description

When creating a relationship field for users the "limit by roles" field generates an error and isn't usable.

### Version

2.8.18

### Testing Instructions

_No response_

### Screenshots / Screencast

image

### Possible Workaround

_No response_

### Site Health Information

_No response_

### Pods Package

_No response_

### PR DESCRIPTION
**Pull request by zrothauser**
## Description

Fixes User role select in DFV. 

## Related GitHub issue(s)

Fixes #6532.

## Testing instructions

See #6532.

## Changelog text for these changes

Bug: List select fields won't error if an option isn't found. 

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- [ ] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

File: ui/js/dfv/src/fields/pick/index.js [hunk 1]
```diff
@@ -73,6 +73,8 @@ const formatValuesForReactSelectComponent = (
 	fieldItemData = [],
 	isMulti = false
 ) => {
+	console.log( 'formatValuesForReactSelectComponent', value, fieldItemData );
```
Comment (sc0ttkclark) [inline ui/js/dfv/src/fields/pick/index.js:76]: Do we still need logging here?
