### PR TITLE
Fix deprecated PHP

### LINKED ISSUE #7145: PHP 8+ deprecated issues
- [ ] Implicit float to int conversion: https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string#array-keys
- [ ] Dynamic properties
- [x] Automatic conversion of false to array is deprecated in \pods\components\Templates\includes\auto-template\Pods_Templates_Auto_Template_Settings.php on line 413

Locations (to be completed):
- https://github.com/pods-framework/pods/blob/main/components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php#L58-L81

### PR DESCRIPTION
**Pull request by JoryHogeveen**
## Description

Changed the prio to an int,

## Related GitHub issue(s)

Fixes #7145 

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- [ ] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

File: components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php [hunk 1]
```diff
@@ -52,7 +52,7 @@ public function hook_content() {
 		foreach ( $possible_pods as $pod_name => $pod ) {
 			$filter = pods_v( 'archive_filter', $pod, '', true );
 			if ( $filter ) {
-				$this->filtered_content[ $filter ] = 10.5;
+				$this->filtered_content[ $filter ] = 10;
```
Comment (sc0ttkclark) [inline components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php:55]: I wonder if we should set this to 11 or not

File: components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php [hunk 2]
```diff
@@ -75,7 +75,7 @@ public function hook_content() {
 			// No need to check for default hooks, this is already done in auto_pods().
 			$filter = pods_v( 'single_filter', $possible_pods[ $pod ], '', true );
 			if ( $filter ) {
-				$this->filtered_content[ $filter ] = 10.5;
+				$this->filtered_content[ $filter ] = 10;
```
Comment (sc0ttkclark) [inline components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php:78]: I wonder if we should set this to 11 or not

Comment (JoryHogeveen) [reply components/Templates/includes/auto-template/Pods_Templates_Auto_Template_Front_End.php:78]: I choose 10 because when I tested `(int) 10.5` it returned 10. But yeah, I had the same thought myself haha.
However, we allow users to override this value so personally I wouldn't worry about it too much and leave it as the WP default value.
