### PR TITLE
Fix error if there is no prefix available

### LINKED ISSUE #5803: Error with empty WP table prefix in PodsData.php
`PHP Warning:  strpos(): Empty needle in /home/***/wp/wp-content/plugins/pods/classes/PodsData.php on line 3058`

On this line, traverse_recurse() checks if the selected table name is a WP table or not by testing for the presence of the WP table prefix at the beginning of the string. In my setup, the table prefix is empty, leading to the error above.

**To Reproduce**

The problem occurs when running a custom WHERE clause pulling a custom field:
```
pods( 'directory_entry', [
	//'where' => "`t.post_title` = 'foobar'" // <<< This works
	'where' => "`entry_type.meta_value` = 'organization'" // <<< This produces the error
] );
```
The code is located in a theme template file. As far as I can tell the WHERE clause works; it produces the right output.

**Expected behavior**
Pods should be flexible enough to allow an empty prefix or state clearly in the setup documentation that this does not work, and then produce a clear error message in the Dashboard.

**Possible Workaround**
Changing line 3058 to check if the prefix is empty bypasses the problem, but I don't know that it's enough to fix it completely or if Pods relies on the presence of a prefix throughout the code.

```
if ( ! empty( $traverse_recurse['params'] ) && ! empty( $traverse_recurse['params']->table ) && ( $wpdb->prefix == '' || 0 === strpos( $traverse_recurse['params']->table, $wpdb->prefix ) ) ) {
```

## Pods Version
2.7.21

## WordPress Environment

<details>
`
### wp-core ###

version: 5.4.2
site_language: en_US
user_language: en_US
timezone: +00:00
permalink: /blogs/%category%/%year%/%postname%/
https_status: true
user_registration: 0
default_comment_status: closed
multisite: false
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: /home/example/dev.example.ca/web/wp
wordpress_size: 45.65 MB (47870665 bytes)
uploads_path: /home/example/dev.example.ca/web/wp/wp-content/uploads
uploads_size: 158.20 MB (165880778 bytes)
themes_path: /home/example/dev.example.ca/web/wp/wp-content/themes
themes_size: 17.49 MB (18339471 bytes)
plugins_path: /home/example/dev.example.ca/web/wp/wp-content/plugins
plugins_size: 122.06 MB (127991952 bytes)
database_size: 11.54 MB (12100430 bytes)
total_size: 354.94 MB (372183296 bytes)

### wp-dropins (1) ###

db-error.php: true

### wp-active-theme ###

name: example (example-theme)
version: 
author: 
author_website: 
parent_theme: none
theme_features: align-wide, editor-font-sizes, editor-color-palette, automatic-feed-links, title-tag, responsive-embeds, menus, html5, post-thumbnails
theme_path: /home/example/dev.example.ca/web/wp/wp-content/themes/example-theme

### wp-themes-inactive (1) ###

Twenty Twenty: version: 1.0, author: the WordPress team (latest version: 1.4)

### wp-plugins-active (18) ###

Crop Thumbnails: version: 1.2.6, author: Volkmar Kantor
Disable Gutenberg Autosave: version: 1.0.7, author: websevendev (latest version: 1.0.8)
Duplicate Post: version: 3.2.4, author: Enrico Battocchi (latest version: 3.2.5)
Events Manager: version: 5.9.7.1, author: Marcus Sykes (latest version: 5.9.8.1)
Forminator: version: 1.11.4, author: WPMU DEV (latest version: 1.13.4)
Gutenberg: version: 7.8.0, author: Gutenberg Team (latest version: 8.7.1)
Gutenberg Ramp: version: 1.1.0, author: Automattic, Inc.
Inline Google Spreadsheet Viewer: version: 0.13.2, author: Meitar Moscovitz <meitarm+wordpress@gmail.com>
Kadence Blocks - Gutenberg Page Builder Toolkit: version: 1.7.10, author: Kadence WP (latest version: 1.8.11)
Loginizer: version: 1.4.8, author: Softaculous (latest version: 1.5.3)
Media Library Assistant: version: 2.81, author: David Lingren (latest version: 2.83)
Pods - Custom Content Types and Fields: version: 2.7.21, author: Pods Framework Team
Redirection: version: 4.7.1, author: John Godley (latest version: 4.8)
Regenerate Thumbnails: version: 3.1.3, author: Alex Mills (Viper007Bond)
Rewrite Rules Inspector: version: 1.2.1, author: Daniel Bachhuber, Automattic
Safe SVG: version: 1.9.8, author: Daryll Doyle (latest version: 1.9.9)
TinyMCE Advanced: version: 5.4.0, author: Andrew Ozz
WP Mail SMTP: version: 1.8.1, author: WPForms (latest version: 2.2.1)

### wp-plugins-inactive (13) ###

Edit Flow: version: 0.9.3, author: Daniel Bachhuber, Scott Bressler, Mohammad Jangda, Automattic, and others (latest version: 0.9.6)
Gutenberg: version: 7.6.1, author: Gutenberg Team (latest version: 8.7.1)
Gutenberg Custom Fields: version: 1.5.6, author: Riad Benguella
Gutenberg Manager: version: 1.5, author: unCommons Team
Hello Dolly: version: 1.7.2, author: Matt Mullenweg
JSON Basic Authentication: version: 0.1, author: WordPress API Team
PressPermit: version: 2.8.8, author: PublishPress (latest version: 3.2.4)
PublishPress Revisions: version: 2.1.6, author: PublishPress (latest version: 2.3.10)
Simple Custom CSS: version: 4.0.3, author: John Regan, Danny Van Kooten (latest version: 4.0.4)
Stylist: version: 0.2.6, author: StylistWP
TablePress: version: 1.10, author: Tobias Bäthge (latest version: 1.11)
WebP Express: version: 0.17.2, author: Bjørn Rosell (latest version: 0.17.4)
WordPress Beta Tester: version: 2.2.7, author: Peter Westwood, Andy Fragen (latest version: 2.2.12)

### wp-media ###

image_editor: WP_Image_Editor_Imagick
imagick_module_version: 1687
imagemagick_version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
imagick_limits: 
	imagick::RESOURCETYPE_AREA: 62 GB
	imagick::RESOURCETYPE_DISK: -1
	imagick::RESOURCETYPE_FILE: 6144
	imagick::RESOURCETYPE_MAP: 62 GB
	imagick::RESOURCETYPE_MEMORY: 31 GB
	imagick::RESOURCETYPE_THREAD: 1
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 9.26

### wp-server ###

server_architecture: Linux 5.4.32-grsec-grsec-plus+ x86_64
httpd_software: Apache
php_version: 7.2.30 64bit
php_sapi: cgi-fcgi
max_input_variables: 1000
time_limit: 120
memory_limit: 1024M
max_input_time: -1
upload_max_size: 50M
php_post_max_size: 55M
curl_version: 7.58.0 OpenSSL/1.1.1
suhosin: false
imagick_availability: true

### wp-database ###

extension: mysqli
server_version: 5.7.28-log
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/example/dev.example.ca/web/wp/wp-content
WP_PLUGIN_DIR: /home/example/dev.example.ca/web/wp/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 1024M
WP_DEBUG: true
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: true
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0
pods-session-save-path: /tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: Yes
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: Yes
pods-object-cache-redis: No
pods-memory-current-usage: 60.245M
pods-memory-current-usage-real: 8.000M
pods-network-wide: No
pods-install-location: /home/example/dev.example.ca/web/wp/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`
</details>

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #5803 

## Description

A DB prefix isn't required for WP and `strpos()` doesn't accept an empty string.

This also makes some minor code enhancements to PodsData.

## PR Checklist

- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: classes/PodsData.php [hunk 1]
```diff
@@ -1806,7 +1799,7 @@ public static function table_create( $table, $fields, $if_not_exists = false ) {
 			$sql .= ' IF NOT EXISTS';
 		}
 
-		$sql .= " `{$wpdb->prefix}" . self::$prefix . "{$table}` ({$fields})";
+		$sql .= " `" . self::get_pods_prefix() . "{$table}` ({$fields})";
```
Comment (tr1b0t) [inline classes/PodsData.php:1802]: :no_entry_sign: String " `" does not require double quotes; use single quotes instead

<sub>hash: 6b11fac6f85f2b72ea41dad1a52cbba5</sub>

File: classes/PodsData.php [hunk 2]
```diff
@@ -1833,12 +1826,7 @@ public static function table_create( $table, $fields, $if_not_exists = false ) {
 	 */
 	public static function table_alter( $table, $changes ) {
 
-		/**
-		 * @var $wpdb wpdb
-		 */
-		global $wpdb;
-
-		$sql = "ALTER TABLE `{$wpdb->prefix}" . self::$prefix . "{$table}` {$changes}";
+		$sql = "ALTER TABLE `" . self::get_pods_prefix() . "{$table}` {$changes}";
```
Comment (tr1b0t) [inline classes/PodsData.php:1829]: :no_entry_sign: String "ALTER TABLE `" does not require double quotes; use single quotes instead

<sub>hash: 1ee7aa9b90e9a8e49f9638cfb9e17690</sub>

File: classes/PodsData.php [hunk 3]
```diff
@@ -1856,12 +1844,7 @@ public static function table_alter( $table, $changes ) {
 	 */
 	public static function table_truncate( $table ) {
 
-		/**
-		 * @var $wpdb wpdb
-		 */
-		global $wpdb;
-
-		$sql = "TRUNCATE TABLE `{$wpdb->prefix}" . self::$prefix . "{$table}`";
+		$sql = "TRUNCATE TABLE `" . self::get_pods_prefix() . "{$table}`";
```
Comment (tr1b0t) [inline classes/PodsData.php:1847]: :no_entry_sign: String "TRUNCATE TABLE `" does not require double quotes; use single quotes instead

<sub>hash: 72d7b496986a9ab9d6584c2160248e71</sub>

File: classes/PodsData.php [hunk 4]
```diff
@@ -1881,12 +1864,7 @@ public static function table_truncate( $table ) {
 	 */
 	public static function table_drop( $table ) {
 
-		/**
-		 * @var $wpdb wpdb
-		 */
-		global $wpdb;
-
-		$sql = "DROP TABLE `{$wpdb->prefix}" . self::$prefix . "{$table}`";
+		$sql = "DROP TABLE `" . self::get_pods_prefix() . "{$table}`";
```
Comment (tr1b0t) [inline classes/PodsData.php:1867]: :no_entry_sign: String "DROP TABLE `" does not require double quotes; use single quotes instead

<sub>hash: 0fe237e7ecb892c22ed19acb0aa40df6</sub>

File: classes/PodsData.php (hunk 1 above)
Comment (sc0ttkclark) [inline classes/PodsData.php:1802]:
```suggestion
		$pods_prefix = self::get_pods_prefix();

		$sql .= " `{$pods_prefix}{$table}` ({$fields})";
```

File: classes/PodsData.php (hunk 2 above)
Comment (sc0ttkclark) [inline classes/PodsData.php:1829]:
```suggestion
		$pods_prefix = self::get_pods_prefix();

		$sql = "ALTER TABLE `{$pods_prefix}{$table}` {$changes}";
```

File: classes/PodsData.php (hunk 3 above)
Comment (sc0ttkclark) [inline classes/PodsData.php:1847]:
```suggestion
		$pods_prefix = self::get_pods_prefix();

		$sql = "TRUNCATE TABLE `{$pods_prefix}{$table}`";
```

File: classes/PodsData.php (hunk 4 above)
Comment (sc0ttkclark) [inline classes/PodsData.php:1867]:
```suggestion
		$pods_prefix = self::get_pods_prefix();

		$sql = "DROP TABLE `{$pods_prefix}{$table}`";
```

File: classes/PodsData.php [hunk 5]
```diff
@@ -3055,7 +3027,14 @@ public function traverse_recurse( $traverse_recurse ) {
 		if ( 0 === $traverse_recurse['depth'] && ! empty( $traverse_recurse['pod'] ) && ! empty( $traverse_recurse ['last_table_info'] ) && isset( $traverse_recurse ['last_table_info']['id'] ) ) {
 			$pod_data = $traverse_recurse ['last_table_info'];
 		} elseif ( empty( $traverse_recurse['pod'] ) ) {
-			if ( ! empty( $traverse_recurse['params'] ) && ! empty( $traverse_recurse['params']->table ) && 0 === strpos( $traverse_recurse['params']->table, $wpdb->prefix ) ) {
+			if (
+				! empty( $traverse_recurse['params'] ) &&
+				! empty( $traverse_recurse['params']->table ) &&
+				(
+					! $wpdb->prefix || // Make sure there is a prefix.
+					0 === strpos( $traverse_recurse['params']->table, $wpdb->prefix )
```
Comment (sc0ttkclark) [inline classes/PodsData.php:3035]:
```suggestion
				! empty( $traverse_recurse['params'] )
				&& ! empty( $traverse_recurse['params']->table )
				&& (
					! $wpdb->prefix // Make sure there is a prefix.
					|| 0 === strpos( $traverse_recurse['params']->table, $wpdb->prefix )
```

**Review by sc0ttkclark — APPROVED** [review]

**Review by sc0ttkclark — APPROVED** [review]
