### PR TITLE
Fix issues with date/time fields and translations

### LINKED ISSUE #5415: Language problem
**Describe the bug**
Since version 2.7.13, when the Site Language of a WordPress install is something other than English, changes that are made to fields from a CPT created with Pods cannot be saved. The native WordPress fields (such as Title, Editor, Author, Featured Image,...) are not affected and are saving.

**To Reproduce**
1. When the WordPress install has not it Site Language set to English Go to a CPT and create or modify an entry.
2. Click on Publish or Update
3. The native Wordpress fields are saved but the fields manage by Pods are unchanged. 

**Expected behavior**
I expected to be able to save CPT content specific to Pods even if the Site Language is set to something else then English, like I could do up to version 2.7.12

**Screenshots**

## Pods Version
Please provide the version of Pods you are running: 2.7.13

## WordPress Environment

<details>

`
### wp-core ###

version: 5.2.2
site_language: en_US
user_language: en_US
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: true
user_registration: false
default_comment_status: closed
multisite: true
user_count: 1
site_count: 1
network_count: 1
dotorg_communication: true

### wp-active-theme ###

name: Two Humans Child Theme
version: 1.0
author: Two Humans
author_website: https://twohumans.net.com
parent_theme: Beaver Builder Theme
theme_features: fl-theme-builder-headers, fl-theme-builder-footers, fl-theme-builder-parts, automatic-feed-links, title-tag, post-thumbnails, woocommerce, align-wide, wp-block-styles, menus, wc-product-gallery-zoom, wc-product-gallery-lightbox, wc-product-gallery-slider, widgets
theme_path: /home/suttonjazz/dev.suttonjazz.com/wp-content/themes/bb-theme

### wp-themes (1) ###

Beaver Builder Theme: version: 1.7.3, author: The Beaver Builder Team

### wp-plugins-active (14) ###

Beaver Builder Plugin (Agency Version): version: 2.2.3.3, author: The Beaver Builder Team
Beaver Themer: version: 1.2.3.4, author: The Beaver Builder Team
Category Order and Taxonomy Terms Order: version: 1.5.7, author: Nsp-Code
Dashboard Welcome for Beaver Builder: version: 1.0.6, author: Beaver Addons, Achal Jain
Health Check & Troubleshooting: version: 1.3.2, author: The WordPress.org community
iThemes Security: version: 7.4.0, author: iThemes
Pods - Custom Content Types and Fields: version: 2.7.13, author: Pods Framework Team
Pods Beaver Themer Add-On: version: 1.3.2, author: Quasel, Pods Framework Team
Pods SEO: version: 2.1, author: Pods Framework Team
Post Types Order: version: 1.9.4.1, author: Nsp Code
PowerPack for Beaver Builder: version: 2.7.1, author: IdeaBox Creations
Ultimate Addons for Beaver Builder: version: 1.18.2, author: Brainstorm Force
UpdraftPlus - Backup/Restore: version: 2.16.15.24, author: UpdraftPlus.Com, DavidAnderson
Yoast SEO: version: 11.6, author: Team Yoast

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
gd_version: bundled (2.1.0 compatible)
ghostscript_version: 8.70

### wp-server ###

server_architecture: Linux 2.6.32-954.3.5.lve1.4.66.el6.x86_64 x86_64
httpd_software: Apache
php_version: 7.1.30 64bit
php_sapi: litespeed
max_input_variables: 1000
time_limit: 30
memory_limit: 256M
max_input_time: -1
upload_max_size: 128M
php_post_max_size: 128M
curl_version: 7.62.0 OpenSSL/1.0.2k
suhosin: false
imagick_availability: false
htaccess_extra_rules: true

### wp-database ###

extension: mysqli
server_version: 5.5.64-MariaDB-cll-lve
client_version: 5.5.62

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: /home/suttonjazz/dev.suttonjazz.com/wp-content
WP_PLUGIN_DIR: /home/suttonjazz/dev.suttonjazz.com/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 256M
WP_DEBUG: false
WP_DEBUG_DISPLAY: true
WP_DEBUG_LOG: false
SCRIPT_DEBUG: false
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache
pods-user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:67.0) Gecko/20100101 Firefox/67.0
pods-session-save-path: /opt/alt/php71/var/lib/php/session
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 65.605M
pods-memory-current-usage-real: 38.000M
pods-network-wide: Yes
pods-install-location: /home/suttonjazz/dev.suttonjazz.com/wp-content/plugins/pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: No
pods-allow-deprecated: Yes
pods-api-cache: Yes

`

</details>

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
{"meta":{"version":"2.7.13","build":1562697556},"pods":{"274":{"id":274,"name":"site","label":"Sites","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"adresse_du_site":{"id":276,"name":"adresse_du_site","label":"Adresse du site","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"telephone_du_site":{"id":277,"name":"telephone_du_site","label":"Téléphone du site","description":"","help":"","class":"","type":"phone","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","phone_format":"999-999-9999 x999","phone_enable_phone_extension":"1","phone_max_length":"25","phone_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","phone_repeatable":"0","phone_placeholder":""},"site_web_du_site":{"id":278,"name":"site_web_du_site","label":"Site Web","description":"","help":"","class":"","type":"website","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"logo_du_site":{"id":279,"name":"logo_du_site","label":"Logo du site","description":"","help":"","class":"","type":"file","weight":3,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Ajouter un fichier","file_modal_title":"Attacher un fichier","file_modal_add_button":"Ajouter un fichier","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"activites_associees":{"id":281,"name":"activites_associees","label":"Activités associées","description":"","help":"","class":"","type":"pick","weight":4,"pick_object":"post_type","pick_val":"spectacle","sister_id":"280","required":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"0","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Site","public":"1","show_ui":"1","supports_title":"1","supports_editor":"0","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"site","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_fl-builder-template-category":"0","built_in_taxonomies_fl-builder-template-type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","menu_icon":"dashicons-location"},"126":{"id":126,"name":"spectacle","label":"Spectacles","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"nom_du_spectacle":{"id":127,"name":"nom_du_spectacle","label":"Nom du spectacle","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"site_du_spectacle":{"id":280,"name":"site_du_spectacle","label":"Site du spectacle","description":"","help":"","class":"","type":"pick","weight":1,"pick_object":"post_type","pick_val":"site","sister_id":"281","required":"0","pick_format_type":"single","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"date_du_spectacle":{"id":139,"name":"date_du_spectacle","label":"Date du spectacle","description":"","help":"","class":"","type":"date","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","date_type":"wp","date_format":"mdy","date_allow_empty":"1","date_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","date_repeatable":"0","date_format_custom":"","date_format_custom_js":""},"heure_du_spectacle":{"id":129,"name":"heure_du_spectacle","label":"Heure du spectacle","description":"","help":"","class":"","type":"text","weight":3,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","seo_analysis_exclude":"0","seo_sitemap_include":"0","text_repeatable":0,"text_placeholder":""},"noms_et_instruments_des_musiciens":{"id":161,"name":"noms_et_instruments_des_musiciens","label":"Noms et instruments des musiciens","description":"","help":"","class":"","type":"text","weight":4,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"video":{"id":162,"name":"video","label":"Vidéo","description":"","help":"","class":"","type":"website","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"site_web":{"id":163,"name":"site_web","label":"Site Web","description":"","help":"","class":"","type":"website","weight":6,"pick_object":"","pick_val":"","sister_id":"","required":"0","website_format":"normal","website_allow_port":"0","website_clickable":"0","website_new_window":"0","website_max_length":"255","website_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","website_repeatable":"0","website_placeholder":""},"prix":{"id":164,"name":"prix","label":"Prix","description":"","help":"","class":"","type":"currency","weight":7,"pick_object":"","pick_val":"","sister_id":"","required":"0","currency_format_type":"number","currency_format_sign":"usd","currency_format_placement":"before","currency_format":"i18n","currency_decimals":"2","currency_decimal_handling":"none","currency_step":"1","currency_min":"0","currency_max":"1000","currency_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","currency_repeatable":"0","currency_placeholder":""},"point_de_vente":{"id":172,"name":"point_de_vente","label":"Point de vente","description":"","help":"","class":"","type":"text","weight":8,"pick_object":"","pick_val":"","sister_id":"","required":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""},"images":{"id":178,"name":"images","label":"Images","description":"","help":"","class":"","type":"file","weight":9,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","file_format_type":"multi","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Ajouter un fichier","file_modal_title":"Attacher un fichier","file_modal_add_button":"Ajouter un fichier","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""}},"show_in_menu":"1","label_singular":"Spectacle","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"spectacle","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"1","built_in_taxonomies_fl-builder-template-category":"0","built_in_taxonomies_fl-builder-template-type":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","menu_icon":"dashicons-tickets-alt","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"append","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","enable_i18n":{"fr_FR":"1"}}}}

**Additional context**
Add any other context about the problem here.

**Possible Workaround**
Change the Site Language to English to create or edit CPT content and revert to the original Site Language when completed.

### LINKED ISSUE #5421: Bug with date format
I use a French WordPress installation with latest Pods and latest WordPress.
This is NOT a regression due to the date fix present in 2.7.14: the bug is here since a long time.

I have a "Date/Time" field set to use format "d/m/Y" ("dmy" is the select option value).

Capture done on July, 13th:
image

If I create a new content, it seems to work (I choose July, 8th):

image

If I save, I get this in the database (still July, 8th):

image

But, if I come back to the content, the date is wrong (July, 8th became August, 7th):

image

My WP Settings > General:

image

### LINKED ISSUE #5444: Custom datetime field in custom content type can not be saved
## Issue Overview
A new content of a newly created custom content type cannot be saved because of a datetime field not saved correctly. This issue happens on a german Wordpress with only the "Twenty Seventeen" Theme and the PODS Plugin activated.

## Expected Behavior
I want to save a custom datetime field in a custom content type.
A click on the datetime field should open a datetime picker to choose date and time.
I should be able to choose a time between 00:00 and 23:59 (german time system) and save the value to the content.

## Current Behavior
Choosing a date with the datetime picker is not a problem. But there is an issue when choosing a time. The datetime picker lets me choose a time from "12:00vorm." to "11:00nachm.".
When I choose one of these times (e.g. 05:00nachm. which corresponds to 05:00pm) and I save the content, all the custom fields are emptied and none is saved.

## Steps to Reproduce (for bugs)
1. Install Wordpress in German
2. Install the PODS-Plugin
3. Create a custom content type with a custom datetime field
4. Create a new content of the newly created content type
5. Choose a date and time using the datetime picker
6. Save the content

## Possible Solution
Option 1: Change the datetime picker for German sites to select times betweeen 00:00 and 23:59. When I manually change the field text from "05:00nachm." to "17:00" the content can be saved.
Option 2: When the datetime picker passes the value to the field it could be rewritten to 05:00pm or 17:00 so that the content can be saved.

## WordPress Environment
WordPress 5.2.2 with "Twenty Seventeen" theme and PODS Version 2.7.14
<details>
```
WordPress Version: 5.2.2

PHP Version: 7.1.30

MySQL Version: 5.5.41

Server Software: Apache/2.4

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36

Session Save Path: /nhldata/953/145953/tmp/phpsession

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 30,396M

Current Memory Usage (real): 2,000M

Pods Network-Wide Activated: No

Pods Install Location: /nhldata04/953/145953/data/web/bernaustaging/htdocs/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Twenty Seventeen

Currently Active Plugins:

Pods - Custom Content Types and Fields: 2.7.14
```
</details>

## Pods Package Export (helpful!)

```
{"meta":{"version":"2.7.14","build":1566314273},"pods":{"26":{"id":26,"name":"agenda","label":"Agenda-Einträge","description":"","type":"post_type","storage":"meta","object":"","alias":"","fields":{"agenda-titlepicture":{"id":28,"name":"agenda-titlepicture","label":"Titelbild","description":"Ein Bild als Aushänger für die Veranstaltung","help":"","class":"","type":"file","weight":0,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"1","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","file_allowed_extensions":""},"agenda-datetime":{"id":29,"name":"agenda-datetime","label":"Datum \/ Zeit","description":"Datum und Zeit der Veranstaltung","help":"","class":"","type":"datetime","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","datetime_type":"format","datetime_format":"mdy","datetime_time_type":"12","datetime_time_format":"h_mma","datetime_time_format_24":"hh_mm","datetime_allow_empty":"1","datetime_html5":"0","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","datetime_repeatable":"0","datetime_format_custom":"","datetime_format_custom_js":"","datetime_time_format_custom":"","datetime_time_format_custom_js":""},"agenda-location":{"id":32,"name":"agenda-location","label":"Ort","description":"Veranstaltungsort","help":"","class":"","type":"text","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","unique":"0","text_repeatable":"0","text_placeholder":""}},"show_in_menu":"1","label_singular":"Agenda-Eintrag","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"agenda","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"draft","supports_author":"0","supports_thumbnail":"0","supports_excerpt":"0","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_post_tag":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"1","pfat_run_outside_loop":"0","pfat_append_single":"replace","pfat_filter_single":"the_content","pfat_append_archive":"append","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"Agenda Template","enable_i18n":{"de_DE":"1"}}},"templates":{"Agenda Template":{"id":39,"name":"Agenda Template","code":"<div class=\"agenda-full\">\r\n\t<h1 class=\"entry-title\">{@post_title}<\/h1>\r\n\t{@agenda-titlepicture._img.large}\r\n\t<p>{@agenda-datetime} - {@agenda-location}<\/p>\r\n\t<p>{@post_content}<\/p>\r\n<\/div>","type":"template","slug":"agenda-template","options":{"_edit_last":"1","_edit_lock":"1566312016:1","admin_only":"","restrict_capability":"","capability_allowed":"","pod_reference":"a:1:{s:3:\"pod\";s:6:\"agenda\";}"}}}}
```

## Workaround or Alternate Solution Until Bug is Addressed
Manually change the text in the field from e.g. "08/14/2019 02:00nachm." to either "08/14/2019 14:00" or "08/14/2019 02:00pm" before saving the content.

## Related Issues and/or PRs
Don't know any.

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #5444
Fixes #5421 
Fixes #5415 (verified by user)

Closes #5445 (makes it obsolete)

## Description

Currently when using jQuery date/time picker saving in other languages doesn't always work correctly due to translations of months and AM/PM.

## How Has This Been Tested?

- Tested all fields for saving in different languages (English, French and German).
- Tested if HTML5 still works for all fields.

## Types of changes

- Make use of the `alt` field in the date/time picker. I added a hidden field to use for saving in which the picker stores the MySQL formatted date (`Y-m-d H:i:s`). This date is send to the server and saved instead of the UI date (translations etc.)
- Removed the code from date.php and time.php templates and make the datetime.php template work for all 3 fields. This prevents a lot of unnecessary duplicate code since these fields are very similar.
- Enhance HTML5 support for `datetime` input type (should be `datetime-local` input type)
- Removed unnecessary long names in JS (it's already wrapped in `jQuery( function () {} );`)
- Made the code a bit more explanatory.

## ChangeLog

* Fix issues with saving date/time fields in other locales.

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: ui/fields/date.php [hunk 1]
```diff
@@ -5,119 +5,4 @@
...
-		<?php
-		} else {
-		?>
-		jQuery( 'input#<?php echo esc_js( $attributes['id'] ); ?>' ).<?php echo esc_js( $method ); ?>( <?php echo esc_js( pods_js_name( $attributes['id'] ) ); ?>_args );
-		<?php
-		}//end if
-		?>
-	} );
-</script>
+include( 'datetime.php' );
```
Comment (sc0ttkclark) [inline ui/fields/date.php]:
```suggestion
include_once( 'datetime.php' );
```

File: ui/fields/date.php [hunk 2]
```diff
@@ -5,119 +5,4 @@
...
-		<?php
-		} else {
-		?>
-		jQuery( 'input#<?php echo esc_js( $attributes['id'] ); ?>' ).<?php echo esc_js( $method ); ?>( <?php echo esc_js( pods_js_name( $attributes['id'] ) ); ?>_args );
-		<?php
-		}//end if
-		?>
-	} );
-</script>
+include_once( 'datetime.php' );
```
Comment (sc0ttkclark) [inline ui/fields/date.php]:
```suggestion
include( 'datetime.php' );
```

File: ui/fields/datetime.php [hunk 3]
```diff
@@ -5,143 +5,192 @@
...
  */
 
+$use_time = ( 'time' === $form_field_type || 'datetime' === $form_field_type );
+$use_date = ( 'date' === $form_field_type || 'datetime' === $form_field_type );
+
 wp_enqueue_script( 'jquery-ui-datepicker' );
-wp_enqueue_script( 'jquery-ui-timepicker' );
 wp_enqueue_style( 'pods-styles' );
-wp_enqueue_style( 'jquery-ui-timepicker' );
+if ( $use_time ) {
```
Comment (sc0ttkclark) [inline ui/fields/datetime.php]:
```suggestion

if ( $use_time ) {
```
