### PR TITLE
Redirect to next Pod admin page if needed

### LINKED ISSUE #4842: Pods Admin Page Provides "No Access" Error when No Pods Exists
## Issue Overview
This is a workflow type issue. If you delete all of your Pods, you no longer actually have a 'manage' Pods screen. After deleting your Pods and clicking on Pods Admin (the main menu for Pods), you will receive the error 'You do not have access to this page' because it's attempting to go to:
/wp-admin/admin.php?page=pods
(and there are no 'pods' to edit)

and it should be attempting to go to:
/wp-admin/admin.php?page=pods-add-new

## Expected Behavior
Clicking on Pods Admin when no Pods exist (or after deleting them) should go to `pods-add-new` not `pods` or maybe `pods` should just handle the redirect itself.

## Current Behavior
Clicking on Pods Admin when no Pods exist after deleting Pods routes to /wp-admin/admin.php?page=pods

## Possible Solution
Page=pods should handle the redirection or check for existence of any pods and send to pods-add-new.

## Steps to Reproduce (for bugs)
1. Create a Pod with Add New, and then go to Edit Pods (/wp-admin/admin.php?page=pods)
2. Delete it (and select Ok) (Confirmation of Pod Deleted Successfully and 'No Pods Found'.
3. Click on Pods Admin Menu (/wp-admin/admin.php?page=pods)
4. "Sorry, you are not allowed to access this page"

Yes, I realize I can click on Add New or the button for Add New and it works properly, but this is a UX issue.

## Todos
- [ ] Tests
- [ ] Documentation

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #4842

## PR Checklist

- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: classes/PodsAdmin.php [hunk 1]
```diff
@@ -573,6 +573,14 @@ public function admin_menu() {
 
 			if ( empty( $all_pods ) ) {
 				unset( $admin_menus['pods'] );
+
+				if ( 'pods' === pods_v( 'page', 'get' ) ) {
+					// Replace `pods` page param with first existing pod page and redirect.
+					$url = add_query_arg( 'page', key( $admin_menus ) );
+					$url = get_site_url( null, $url );
+					wp_redirect( $url );
```
Comment (tr1b0t) [inline classes/PodsAdmin.php:581]: :warning: wp_redirect() found. Using wp_safe_redirect(), along with the allowed_redirect_hosts filter if needed, can help avoid any chances of malicious redirects within code. It is also important to remember to call exit() after a redirect so that no other unwanted code is executed.

<sub>hash: 437ac422441dc926853f890489cd6508</sub>

**Review by tr1b0t — COMMENTED** [review]
:warning: 1 warning(s)

File: classes/PodsAdmin.php [hunk 2]
```diff
@@ -573,6 +573,14 @@ public function admin_menu() {
 
 			if ( empty( $all_pods ) ) {
 				unset( $admin_menus['pods'] );
+
+				if ( 'pods' === pods_v( 'page', 'get' ) ) {
+					// Replace `pods` page param with first existing pod page and redirect.
+					$url = add_query_arg( 'page', key( $admin_menus ) );
+					$url = get_site_url( null, $url );
+					wp_safe_redirect( $url );
+					die;
```
Comment (sc0ttkclark) [inline classes/PodsAdmin.php:582]:
```suggestion
					die();
```

File: classes/PodsAdmin.php [hunk 3]
```diff
@@ -573,6 +573,14 @@ public function admin_menu() {
 
 			if ( empty( $all_pods ) ) {
 				unset( $admin_menus['pods'] );
+
+				if ( 'pods' === pods_v( 'page', 'get' ) ) {
+					// Replace `pods` page param with first existing pod page and redirect.
+					$url = add_query_arg( 'page', key( $admin_menus ) );
+					$url = get_site_url( null, $url );
+					wp_safe_redirect( $url );
```
Comment (sc0ttkclark) [inline classes/PodsAdmin.php:581]:
```suggestion

					wp_safe_redirect( $url );
```

**Review by sc0ttkclark — APPROVED** [review]
