### PR TITLE
Fix PHP Deprecated: strlen(): Passing null

### LINKED ISSUE #7075: PHP Deprecated: strlen(): Passing null to parameter #1 ($string) of type string is deprecated in classes/Pods.php
### Description

https://wordpress.org/support/topic/tons-of-php-deprecated-strlen-messages-in-error-log-under-php-8-x/

### Version

2.9.13

### Testing Instructions

_No response_

### Screenshots / Screencast

_No response_

### Possible Workaround

_No response_

### Site Health Information

_No response_

### Pods Package

_No response_

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Set empty string as default

## Related GitHub issue(s)

Fixes #7075

## PR checklist

- [ ] I have tested my own code to confirm it works as I intended.
- [ ] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [ ] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- [ ] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

File: classes/Pods.php [hunk 1]
```diff
@@ -1717,7 +1717,7 @@ public function field( $name, $single = null, $raw = false ) {
 					$post_ID = $this->id();
 				}
 
-				$filter = pods_v( 'display_filter', $field_data );
+				$filter = pods_v( 'display_filter', $field_data, '' );
```
Comment (sc0ttkclark) [inline classes/Pods.php:1720]:
```suggestion
				$filter = pods_v( 'display_filter', $field_data, '', true );
```
This will ensure it always ends up the blank string if it's empty-ish

**Review by sc0ttkclark — CHANGES_REQUESTED** [review]
This is good, just want to be sure we cover more cases

**Review by sc0ttkclark — APPROVED** [review]
