### PR TITLE
Fix/Enhance ACT list view pagination

### LINKED ISSUE #5509: Pagination URL is wrong for child type
## Issue Overview
I created an ACT called `product_attribute`. I added `edit.php?post_type=product` in the Parent Menu ID option. I can display the Product Attributes by going to `/wp-admin/edit.php?post_type=product&page=pods-manage-product_attribute` but when I click on the next page button, it goes to `/wp-admin/edit.php?page=pods-manage-product_attribute&pg=2` and I get a _Sorry, you are not allowed to access this page_. Looks like it should be `/wp-admin/edit.php?post_type=product&page=pods-manage-product_attribute&pg=2` instead.

## Expected Behavior
When I click on the next page button, it should go to `/wp-admin/edit.php?post_type=product&page=pods-manage-product_attribute&pg=2` and display the second page for Product Attributes.

## Current Behavior
When I click on the next page button, it goes to `/wp-admin/edit.php?page=pods-manage-product_attribute&pg=2` and I get a _Sorry, you are not allowed to access this page_.

## Steps to Reproduce (for bugs)

1. Create a Custom Post Type called product.
2. Create an Advanced Content Type called product_attribute.
3. In Product, add a field called attributes of type relationship,related to product_attribute.
4. In Product Attribute, add a field called products of type relationship, related to product.
5. In Admin UI, set Parent Menu ID to `edit.php?post_type=product`
6. Add enough product attributes to have 2 pages in `/wp-admin/edit.php?post_type=product&page=pods-manage-product_attribute`
7. Click on the Next Page button.

## Possible Solution
Add the parameter `post_type=product` when navigating between pages.

## WordPress Environment

<details>
WordPress Version: 5.2.4

PHP Version: 7.0.15

MySQL Version: 5.6.35

Server Software: Apache/2.2.31 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.0.15 mod_ssl/2.2.31 OpenSSL/1.0.2j DAV/2 mod_fastcgi/2.4.6 mod_perl/2.0.9 Perl/v5.24.0

Your User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36

Session Save Path: /Applications/MAMP/tmp/php

Session Save Path Exists: Yes

Session Save Path Writeable: Yes

Session Max Lifetime: 1440

Opcode Cache:

Apc: No
Memcached: No
OPcache: No
Redis: No
Object Cache:

APC: No
APCu: No
Memcache: No
Memcached: No
Redis: No
WPDB Prefix: wp_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 55.520M

Current Memory Usage (real): 10.000M

Pods Network-Wide Activated: No

Pods Install Location: /Users/benjamindurin/lmi2019/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Movedo Child

Currently Active Plugins:

Contact Form 7: 5.1.4
Data Tables Generator by Supsystic: 1.9.80
Disable Gutenberg: 1.9
Duplicate Post: 3.2.3
Movedo Extension: 3.2
Pods - Custom Content Types and Fields: 2.7.15
Resize Image After Upload: 1.8.6
Super Forms - Drag & Drop Form Builder: 4.7.63
Who Stole the Text Justify Button ?!: 1.0
WPBakery Page Builder: 6.0.5
</details>

## Pods Package Export (helpful!)
{"meta":{"version":"2.7.15","build":1571848548},"pods":{"268":{"id":268,"name":"product_attribute","label":"Product Attributes","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"name":{"id":269,"name":"name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_repeatable":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":""},"value":{"id":274,"name":"value","label":"Value","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"order":{"id":275,"name":"order","label":"Order","description":"","help":"","class":"","type":"number","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"i18n","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0","number_placeholder":""},"products":{"id":686,"name":"products","label":"products","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"product","sister_id":"291","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"pandarepeaterfield_table":"product","pandarepeaterfield_field_width":"100","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"pandarf_order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Product Attribute","pod_index":"name","hierarchical":"0","ui_style":"post_type","menu_position":"0","ui_actions_enabled":["add","edit","duplicate","delete"],"ui_reorder_field":"menu_order","ui_fields_manage":["name","value"],"menu_location_custom":"edit.php?post_type=product","ui_filters":["name","value"]},"264":{"id":264,"name":"product_brand","label":"Product Brands","description":"","type":"taxonomy","storage":"table","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Product Brand","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"product_brand","query_var":"0","sort":"0","built_in_post_types_area-item":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_portfolio":"0","built_in_post_types_post":"0","built_in_post_types_super_contact_entry":"0","built_in_post_types_super_form":"0","built_in_post_types_testimonial":"0","built_in_post_types_user_request":"0","built_in_post_types_vc4_templates":"0","built_in_post_types_vc_grid_item":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpcf7_contact_form":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_product":"1"},"263":{"id":263,"name":"product_category","label":"Product Categories","description":"","type":"taxonomy","storage":"table","object":"","alias":"","fields":[],"show_in_menu":"1","label_singular":"Product Category","public":"1","show_ui":"1","hierarchical":"1","rewrite":"1","rewrite_with_front":"1","rewrite_hierarchical":"1","capability_type":"default","capability_type_custom":"product_category","query_var":"0","sort":"0","built_in_post_types_area-item":"0","built_in_post_types_custom_css":"0","built_in_post_types_customize_changeset":"0","built_in_post_types_oembed_cache":"0","built_in_post_types_page":"0","built_in_post_types_portfolio":"0","built_in_post_types_post":"0","built_in_post_types_super_contact_entry":"0","built_in_post_types_super_form":"0","built_in_post_types_testimonial":"0","built_in_post_types_user_request":"0","built_in_post_types_vc4_templates":"0","built_in_post_types_vc_grid_item":"0","built_in_post_types_wp_block":"0","built_in_post_types_wpcf7_contact_form":"0","built_in_post_types_attachment":"0","menu_location":"default","menu_position":"0","show_in_nav_menus":"1","show_tagcloud":"1","show_tagcloud_in_edit":"1","show_in_quick_edit":"1","show_admin_column":"0","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_archive":"append","rest_enable":"0","read_all":"0","write_all":"0","built_in_post_types_product":"1"},"276":{"id":276,"name":"product_description","label":"Product Descriptions","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"name":{"id":277,"name":"name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"0","text_repeatable":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","text_placeholder":""},"value":{"id":282,"name":"value","label":"Value","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":"0","text_placeholder":""},"order":{"id":283,"name":"order","label":"Order","description":"","help":"","class":"","type":"number","weight":2,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"i18n","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"number_repeatable":"0","number_placeholder":""},"products":{"id":687,"name":"products","label":"products","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"post_type","pick_val":"product","sister_id":"292","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"pandarepeaterfield_table":"product","pandarepeaterfield_field_width":"100","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"pandarf_order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Product Description","pod_index":"name","hierarchical":"0","ui_style":"post_type","menu_position":"0","ui_actions_enabled":["add","edit","duplicate","delete"],"ui_reorder_field":"menu_order","ui_fields_manage":["name"],"menu_location_custom":"edit.php?post_type=product"},"294":{"id":294,"name":"product_photo","label":"Product Photos","description":"","type":"pod","storage":"table","object":"","alias":"","fields":{"name":{"id":1393,"name":"name","label":"Name","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"text_repeatable":0,"text_placeholder":""},"media":{"id":300,"name":"media","label":"media","description":"","help":"","class":"","type":"file","weight":1,"pick_object":"custom-simple","pick_val":"","sister_id":"","required":"0","unique":"0","file_format_type":"single","file_uploader":"attachment","file_attachment_tab":"upload","file_edit_title":"1","file_show_edit_link":"0","file_linked":"0","file_limit":"0","file_restrict_filesize":"10MB","file_type":"images","file_field_template":"rows","file_add_button":"Add File","file_modal_title":"Attach a file","file_modal_add_button":"Add File","file_wp_gallery_output":"0","file_wp_gallery_link":"post","file_wp_gallery_columns":"1","file_wp_gallery_random_sort":"0","file_wp_gallery_size":"thumbnail","pick_post_status":["publish"],"pandarepeaterfield_table":"product","pandarepeaterfield_field_width":"100","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"pandarf_order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"file_allowed_extensions":""},"products":{"id":688,"name":"products","label":"products","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"post_type","pick_val":"product","sister_id":"301","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"pandarepeaterfield_table":"product","pandarepeaterfield_field_width":"100","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"pandarf_order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""}},"show_in_menu":"1","label_singular":"Product Photo","pod_index":"id","hierarchical":"0","ui_style":"post_type","menu_position":"0","ui_actions_enabled":["add","edit","duplicate","delete"],"ui_reorder_field":"menu_order","ui_fields_manage":{"0":"media","2":"id"},"menu_location_custom":"edit.php?post_type=product"},"265":{"id":265,"name":"product","label":"Products","description":"","type":"post_type","storage":"table","object":"","alias":"","fields":{"reference":{"id":266,"name":"reference","label":"Reference","description":"","help":"","class":"","type":"text","weight":0,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":"0","text_placeholder":""},"model_number":{"id":267,"name":"model_number","label":"Model Number","description":"","help":"","class":"","type":"text","weight":1,"pick_object":"","pick_val":"","sister_id":"","required":"1","unique":"1","text_allow_shortcode":"0","text_allow_html":"0","text_allowed_html_tags":"strong em a ul ol li b i","text_max_length":"255","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","text_repeatable":"0","text_placeholder":""},"attributes":{"id":291,"name":"attributes","label":"Attributes","description":"","help":"","class":"","type":"pick","weight":2,"pick_object":"pod","pick_val":"product_attribute","sister_id":"686","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"pandarepeaterfield_table":"product_attribute","pandarepeaterfield_field_width":"25","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_display":"@value","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_where":"","pick_orderby":"","pick_groupby":""},"descriptions":{"id":292,"name":"descriptions","label":"Descriptions","description":"","help":"","class":"","type":"pick","weight":3,"pick_object":"pod","pick_val":"product_description","sister_id":"687","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"pandarepeaterfield_table":"product_description","pandarepeaterfield_field_width":"25","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_display":"","pick_where":"","pick_orderby":"","pick_groupby":""},"photos":{"id":301,"name":"photos","label":"Photos","description":"","help":"","class":"","type":"pick","weight":4,"pick_object":"pod","pick_val":"product_photo","sister_id":"688","required":"0","unique":"0","pick_format_type":"multi","pick_format_single":"dropdown","pick_format_multi":"checkbox","pick_allow_add_new":"1","pick_taggable":"0","pick_show_icon":"1","pick_show_edit_link":"1","pick_show_view_link":"1","pick_limit":"0","pick_user_role":[],"pick_post_status":["publish"],"pandarepeaterfield_table":"product_photo","pandarepeaterfield_field_width":"100","pandarepeaterfield_entry_limit":"0","pandarepeaterfield_enable_load_more":"0","pandarepeaterfield_initial_amount":"10","pandarepeaterfield_enable_trash":"0","pandarepeaterfield_order_by":"pandarf_order","pandarepeaterfield_order":"ASC","pandarepeaterfield_display_order_info":"0","pandarepeaterfield_apply_admin_columns":"0","pandarepeaterfield_allow_reassign":"0","pandarepeaterfield_public_access":"0","subscriber":"0","admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","pick_orderby":"name","pick_display":"@name","pick_select_text":"","pick_table_id":"","pick_table_index":"","pick_where":"","pick_groupby":""},"table_id":{"id":6310,"name":"table_id","label":"Table ID","description":"","help":"","class":"","type":"number","weight":5,"pick_object":"","pick_val":"","sister_id":"","required":"0","unique":"0","number_format_type":"number","number_format":"i18n","number_decimals":"0","number_format_soft":"0","number_step":"1","number_min":"0","number_max":"100","number_max_length":"12","pick_post_status":["publish"],"admin_only":"0","restrict_role":"0","restrict_capability":"0","hidden":"0","read_only":"0","roles_allowed":["administrator"],"rest_read":"0","rest_write":"0","rest_pick_response":"array","rest_pick_depth":"2","number_repeatable":"0","number_placeholder":""}},"show_in_menu":"1","label_singular":"Product","public":"1","show_ui":"1","supports_title":"1","supports_editor":"1","publicly_queryable":"1","exclude_from_search":"0","capability_type":"post","capability_type_custom":"product","capability_type_extra":"1","has_archive":"0","hierarchical":"0","rewrite":"1","rewrite_with_front":"1","rewrite_feeds":"0","rewrite_pages":"1","query_var":"1","can_export":"1","default_status":"publish","supports_author":"0","supports_thumbnail":"1","supports_excerpt":"1","supports_trackbacks":"0","supports_custom_fields":"0","supports_comments":"0","supports_revisions":"0","supports_page_attributes":"0","supports_post_formats":"0","built_in_taxonomies_category":"0","built_in_taxonomies_link_category":"0","built_in_taxonomies_portfolio_category":"0","built_in_taxonomies_portfolio_field":"0","built_in_taxonomies_post_tag":"0","built_in_taxonomies_product_brand":"1","built_in_taxonomies_product_category":"1","built_in_taxonomies_testimonial_category":"0","menu_position":"0","show_in_nav_menus":"1","show_in_admin_bar":"1","pfat_enable":"0","pfat_run_outside_loop":"0","pfat_append_single":"replace","pfat_filter_single":"the_content","pfat_append_archive":"replace","pfat_filter_archive":"the_content","rest_enable":"0","read_all":"0","write_all":"0","pfat_single":"Product template"}}}

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #5509 

## Screenshots (jpeg or gifs if applicable):
Previous:
image

PR:
image

## ChangeLog

* Fix & Enhance ACT list view pagination

## Checklist:
- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.

### CODE REVIEW

File: classes/PodsUI.php [hunk 1]
```diff
@@ -4653,9 +4655,13 @@ public function pagination( $header = false ) {
 
 		if ( false !== $this->pagination ) {
 			if ( 1 < $total_pages ) {
+				$first_link = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 6da1b1864943789bd549a5e4363dd6a8</sub>

File: classes/PodsUI.php [hunk 2]
```diff
@@ -4653,9 +4655,13 @@ public function pagination( $header = false ) {
...
+				$prev_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 86907a983e574eee0da23e9906b89ae4</sub>

File: classes/PodsUI.php [hunk 3]
```diff
@@ -4653,9 +4655,13 @@ public function pagination( $header = false ) {
...
+				$next_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: f41b99799f529ecf99ead7928a6b0ce6</sub>

File: classes/PodsUI.php [hunk 4]
```diff
@@ -4653,9 +4655,13 @@ public function pagination( $header = false ) {
...
+				$last_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 3a2b2ea547f03ddcfb6e2cace87b920e</sub>

File: classes/PodsUI.php [hunk 5]
```diff
@@ -4653,9 +4655,13 @@ public function pagination( $header = false ) {
...
 				?>
-				<a class="first-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' ); ?>">&laquo;</a>
-				<a class="prev-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) ); ?>">&lsaquo;</a>
+				<a class="button first-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo $first_link; ?>">&laquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Inline IF statements are not allowed
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$first_link'.

<sub>hash: 77b13dfab9b0459a8f31dbcb85f6501f</sub>

File: classes/PodsUI.php [hunk 6]
```diff
@@ -4653,9 +4655,13 @@ public function pagination( $header = false ) {
...
+				<a class="button prev-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo $prev_link; ?>">&lsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Inline IF statements are not allowed
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$prev_link'.

<sub>hash: 188250d0fad934518b089939762440bd</sub>

File: classes/PodsUI.php [hunk 7]
```diff
@@ -4681,8 +4687,8 @@ public function pagination( $header = false ) {
 					<?php
 				}//end if
 				?>
-				<a class="next-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) ); ?>">&rsaquo;</a>
-				<a class="last-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>'" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages ); ?>">&raquo;</a>
+				<a class="button next-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo $next_link; ?>">&rsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Inline IF statements are not allowed
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$next_link'.

<sub>hash: 200d952f03d15bfa2f575a5bab4af506</sub>

File: classes/PodsUI.php [hunk 8]
```diff
@@ -4681,8 +4687,8 @@ public function pagination( $header = false ) {
...
+				<a class="button last-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>" href="<?php echo $last_link; ?>">&raquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Inline IF statements are not allowed
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$last_link'.

<sub>hash: 87f0e2eef6414b9151ac0ec1f18d5606</sub>

File: classes/PodsUI.php [hunk 9]
```diff
@@ -4634,6 +4634,8 @@ public function pagination( $header = false ) {
 				'filter_*',
 				'view' . $this->num,
 				'page' . $this->num,
+				'post_type',
+				'taxonomy',
```
Comment (sc0ttkclark) [inline classes/PodsUI.php]:
```suggestion
				'taxonomy',
				'action',
```

File: classes/PodsUI.php [hunk 10]
```diff
@@ -4634,6 +4634,9 @@ public function pagination( $header = false ) {
...
+				'action',
```
Comment (sc0ttkclark) [inline classes/PodsUI.php]:
```suggestion
				'action' . $this->num,
```

File: classes/PodsUI.php [hunk 11]
```diff
@@ -4653,9 +4656,13 @@ public function pagination( $header = false ) {
 
 		if ( false !== $this->pagination ) {
 			if ( 1 < $total_pages ) {
+				$first_link = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' );
```
Comment (sc0ttkclark) [inline classes/PodsUI.php]:
```suggestion
				$separator = '?';

				if ( $append ) {
					$separator = '&';
				}

				$first_link = esc_url( $request_uri . $separator . 'pg' . $this->num . '=1' );
```

File: classes/PodsUI.php [hunk 12]
```diff
@@ -4653,9 +4656,13 @@ public function pagination( $header = false ) {
...
+				$prev_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) );
```
Comment (sc0ttkclark) [inline classes/PodsUI.php]:
```suggestion
				$prev_link  = esc_url( $request_uri . $separator . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) );
```

File: classes/PodsUI.php [hunk 13]
```diff
@@ -4653,9 +4656,13 @@ public function pagination( $header = false ) {
...
+				$next_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) );
```
Comment (sc0ttkclark) [inline classes/PodsUI.php]:
```suggestion
				$next_link  = esc_url( $request_uri . $separator . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) );
```

File: classes/PodsUI.php [hunk 14]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
 
 		if ( false !== $this->pagination ) {
 			if ( 1 < $total_pages ) {
+				$first_link    = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Equals sign not aligned with surrounding assignments; expected 1 space but found 4 spaces
* :no_entry_sign: Inline IF statements are not allowed

<sub>hash: e24010a1995caea163212a8024182cc7</sub>

File: classes/PodsUI.php [hunk 15]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				$prev_link     = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Equals sign not aligned with surrounding assignments; expected 2 spaces but found 5 spaces
* :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 54448766b9605957b673acef717e6618</sub>

File: classes/PodsUI.php [hunk 16]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				$next_link     = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Equals sign not aligned with surrounding assignments; expected 2 spaces but found 5 spaces
* :no_entry_sign: Inline IF statements are not allowed

<sub>hash: a5cd5fd24b603ca4ab57e0735b02ed3a</sub>

File: classes/PodsUI.php [hunk 17]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				$last_link     = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Equals sign not aligned with surrounding assignments; expected 2 spaces but found 5 spaces
* :no_entry_sign: Inline IF statements are not allowed

<sub>hash: bd378ac23e46be5682b933302071498c</sub>

File: classes/PodsUI.php [hunk 18]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				if ( 1 < $this->page ) {
+					$classes .= ' disabled';
+				}
+				if ( is_admin() ) {
+					$classes .= ' button';
+				}
 				?>
-				<a class="first-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' ); ?>">&laquo;</a>
-				<a class="prev-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) ); ?>">&lsaquo;</a>
+				<a class="first-page<?php esc_attr_e( $classes ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo $first_link; ?>">&laquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Missing $domain arg.
* :no_entry_sign: The $text arg must be a single string literal, not "$classes".
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$first_link'.

<sub>hash: 9d402a20fbb051bb57d0d321c8b8a335</sub>

File: classes/PodsUI.php [hunk 19]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				<a class="prev-page<?php esc_attr_e( $classes ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo $prev_link; ?>">&lsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Missing $domain arg.
* :no_entry_sign: The $text arg must be a single string literal, not "$classes".
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$prev_link'.

<sub>hash: b2ae3dc9730b78874094ac1c5736f29c</sub>

File: classes/PodsUI.php [hunk 20]
```diff
@@ -4680,9 +4695,16 @@ public function pagination( $header = false ) {
...
+				if ( $this->page < $total_pages ) {
+					$classes .= ' disabled';
+				}
+				if ( is_admin() ) {
+					$classes .= ' button';
+				}
 				?>
-				<a class="next-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) ); ?>">&rsaquo;</a>
-				<a class="last-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>'" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages ); ?>">&raquo;</a>
+				<a class="next-page<?php esc_attr_e( $classes ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo $next_link; ?>">&rsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Missing $domain arg.
* :no_entry_sign: The $text arg must be a single string literal, not "$classes".
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$next_link'.

<sub>hash: 19406f44241942ccffac03a95511ffc7</sub>

File: classes/PodsUI.php [hunk 21]
```diff
@@ -4680,9 +4695,16 @@ public function pagination( $header = false ) {
...
+				<a class="last-page<?php esc_attr_e( $classes ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>" href="<?php echo $last_link; ?>">&raquo</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :no_entry_sign: Missing $domain arg.
* :no_entry_sign: The $text arg must be a single string literal, not "$classes".
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$last_link'.

<sub>hash: 7b8bfc70c046143398507fcefd35d90d</sub>

File: classes/PodsUI.php [hunk 22]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
 
 		if ( false !== $this->pagination ) {
 			if ( 1 < $total_pages ) {
+				$first_link = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 86907a983e574eee0da23e9906b89ae4</sub>

File: classes/PodsUI.php [hunk 23]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				$prev_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: f41b99799f529ecf99ead7928a6b0ce6</sub>

File: classes/PodsUI.php [hunk 24]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				$next_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 3a2b2ea547f03ddcfb6e2cace87b920e</sub>

File: classes/PodsUI.php [hunk 25]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				$last_link  = esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages );
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: Inline IF statements are not allowed

<sub>hash: 634be925cb947565bdc109e9978ad771</sub>

File: classes/PodsUI.php [hunk 26]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				if ( 1 < $this->page ) {
+					$classes .= ' disabled';
+				}
+				if ( is_admin() ) {
+					$classes .= ' button';
+				}
 				?>
-				<a class="first-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' ); ?>">&laquo;</a>
-				<a class="prev-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) ); ?>">&lsaquo;</a>
+				<a class="first-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo $first_link; ?>">&laquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$first_link'.

<sub>hash: f49250a14ebf97e7e822d6d3131795e1</sub>

File: classes/PodsUI.php [hunk 27]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				<a class="prev-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo $prev_link; ?>">&lsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$prev_link'.

<sub>hash: 9d768319225b9d01928b17a5f7cf8f16</sub>

File: classes/PodsUI.php [hunk 28]
```diff
@@ -4680,9 +4695,16 @@ public function pagination( $header = false ) {
...
+				if ( $this->page < $total_pages ) {
+					$classes .= ' disabled';
+				}
+				if ( is_admin() ) {
+					$classes .= ' button';
+				}
 				?>
-				<a class="next-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) ); ?>">&rsaquo;</a>
-				<a class="last-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>'" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages ); ?>">&raquo;</a>
+				<a class="next-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo $next_link; ?>">&rsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$next_link'.

<sub>hash: 8e2ac9bbed7455592bc3d3d2211c9da4</sub>

File: classes/PodsUI.php [hunk 29]
```diff
@@ -4680,9 +4695,16 @@ public function pagination( $header = false ) {
...
+				<a class="last-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>" href="<?php echo $last_link; ?>">&raquo</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$last_link'.

<sub>hash: 194e3ed951384b5274f08929f5b1457f</sub>

File: classes/PodsUI.php [hunk 30]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				if ( 1 >= $this->page ) {
+					$classes .= ' disabled';
+				}
+				if ( is_admin() ) {
+					$classes .= ' button';
+				}
 				?>
-				<a class="first-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=1' ); ?>">&laquo;</a>
-				<a class="prev-page<?php echo esc_attr( ( 1 < $this->page ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . max( $this->page - 1, 1 ) ); ?>">&lsaquo;</a>
+				<a class="first-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the first page', 'pods' ); ?>" href="<?php echo $first_link; ?>">&laquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$first_link'
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$first_link'.

<sub>hash: 3039135f92ba7e10cd6d09e63498b6d3</sub>

File: classes/PodsUI.php [hunk 31]
```diff
@@ -4653,9 +4656,21 @@ public function pagination( $header = false ) {
...
+				<a class="prev-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the previous page', 'pods' ); ?>" href="<?php echo $prev_link; ?>">&lsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$prev_link'
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$prev_link'.

<sub>hash: 81a73ccc00f46f87a1dcc9b7eed79f6d</sub>

File: classes/PodsUI.php [hunk 32]
```diff
@@ -4680,9 +4695,16 @@ public function pagination( $header = false ) {
...
+				if ( $this->page >= $total_pages ) {
+					$classes .= ' disabled';
+				}
+				if ( is_admin() ) {
+					$classes .= ' button';
+				}
 				?>
-				<a class="next-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . min( $this->page + 1, $total_pages ) ); ?>">&rsaquo;</a>
-				<a class="last-page<?php echo esc_attr( ( $this->page < $total_pages ) ? '' : ' disabled' ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>'" href="<?php echo esc_url( $request_uri . ( $append ? '&' : '?' ) . 'pg' . $this->num . '=' . $total_pages ); ?>">&raquo;</a>
+				<a class="next-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the next page', 'pods' ); ?>" href="<?php echo $next_link; ?>">&rsaquo;</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$next_link'
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$next_link'.

<sub>hash: 1a5f712b3ec907d611f8733168790a00</sub>

File: classes/PodsUI.php [hunk 33]
```diff
@@ -4680,9 +4695,16 @@ public function pagination( $header = false ) {
...
+				<a class="last-page<?php echo esc_attr( $classes ); ?>" title="<?php esc_attr_e( 'Go to the last page', 'pods' ); ?>" href="<?php echo $last_link; ?>">&raquo</a>
```
Comment (tr1b0t) [inline classes/PodsUI.php]: * :warning: Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$last_link'
* :no_entry_sign: All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '$last_link'.

<sub>hash: f7d756d3b57c9673db8ac1c13a02dad9</sub>
