### PR TITLE
Fixes for showing/hiding some of the List View specific options

### LINKED ISSUE #4038: 2.7/feature Editing List View Field doesn't show container for 'Show Icons, Show Edit, Show View' until you change the field type.
2.7/feature Editing List View Field doesn't show container for 'Show Icons, Show Edit, Show View' until you change the field type. submitted via Slack by jimtrue

PR: #4415

### PR DESCRIPTION
**Pull request by pglewis**
Fixes #4038 

This is a two-parter: 

- [x] Don't check multi-format dependencies if single select is the type and vice versa
- [x] Come up with a way to run dependency checks again when the selection type changes

### CODE REVIEW

**Comment by pglewis** [comment]
Note that this workaround will be a stop-gap for 2.7.  Dynamic dependency checking will be reworked for 2.8.

File: classes/PodsForm.php [hunk 1]
```diff
@@ -825,68 +825,68 @@ public static function field_setup( $field = null, $core_defaults = null, $type
      * @param array $options array( 'depends-on' => ..., 'excludes-on' => ...)
      * @param string $prefix
      *
-     * @return string
+     * @return array
```
Comment (pglewis) [inline classes/PodsForm.php]: The changes in this commit were in preparation for some more changes to be made but that turned out to be unnecessary.
