### PR TITLE
Fix Pod form - #5946

### LINKED ISSUE #5946: [Pods 2.8 Bug] Pod form
## Pods 2.8 version

2.8.0-b-1

## Description

Pods form doesn't work as usual. 

## Testing instructions

1. Create a pod, normal or advanced, or use my exported Pods package below.
2. On the page template, add this code: $pod = pods( 'member' ); echo $pod->form( ); The Member pod is from my exported package.	
Here is the tutorials on the Pods site: https://pods.io/docs/code/pods/form/

## Expected behavior

A proper form, not just some input boxes.

## Screenshots / screencast
Working version on Pods 2.7
http://176.32.230.22/codingpanda.co.uk/wp-content/uploads/pods-form-on-2-7.png
No working on Pods 2.8
http://176.32.230.22/codingpanda.co.uk/wp-content/uploads/pods-form-on-2-8.png
## Other super helpful information

<details>
<summary>WordPress Environment</summary>
  
`
### wp-core ###

version: 5.6.1
site_language: en_GB
user_language: en_GB
timezone: Europe/London
permalink: /%year%/%monthnum%/%day%/%postname%/
https_status: false
multisite: false
user_registration: 0
blog_public: 0
default_comment_status: open
environment_type: production
user_count: 1
dotorg_communication: true

### wp-paths-sizes ###

wordpress_path: F:\xampp\htdocs\pprf-demo
wordpress_size: 77.03 MB (80772505 bytes)
uploads_path: F:\xampp\htdocs\pprf-demo/wp-content/uploads
uploads_size: 0.00 B (0 bytes)
themes_path: F:\xampp\htdocs\pprf-demo/wp-content/themes
themes_size: 8.02 MB (8411420 bytes)
plugins_path: F:\xampp\htdocs\pprf-demo/wp-content/plugins
plugins_size: 9.66 MB (10129624 bytes)
database_size: 2.83 MB (2965504 bytes)
total_size: 97.54 MB (102279053 bytes)

### wp-active-theme ###

name: Twenty Twenty (twentytwenty)
version: 1.6
author: the WordPress team
author_website: https://en-gb.wordpress.org/
parent_theme: none
theme_features: core-block-patterns, automatic-feed-links, custom-background, post-thumbnails, custom-logo, title-tag, html5, align-wide, responsive-embeds, customize-selective-refresh-widgets, editor-color-palette, editor-font-sizes, widgets, menus, editor-style
theme_path: F:\xampp\htdocs\pprf-demo/wp-content/themes/twentytwenty
auto_update: Disabled

### wp-themes-inactive (3) ###

Twenty Nineteen: version: 1.8, author: WordPress Team (latest version: 1.9), Auto-updates disabled
Twenty Seventeen: version: 2.5, author: the WordPress team, Auto-updates disabled
Twenty Twenty-One: version: 1.0, author: the WordPress team (latest version: 1.1), Auto-updates disabled

### wp-plugins-active (2) ###

Panda Pods Repeater Field: version: 1.4.8, author: Dongjie Xu, Auto-updates disabled
Pods - Custom Content Types and Fields: version: 2.7.26, author: Pods Framework Team, Auto-updates disabled

### wp-media ###

image_editor: WP_Image_Editor_GD
imagick_module_version: Not available
imagemagick_version: Not available
file_uploads: File uploads is turned off
post_max_size: 250M
upload_max_filesize: 250M
max_effective_size: 250 MB
max_file_uploads: 20
gd_version: bundled (2.1.0 compatible)
ghostscript_version: not available

### wp-server ###

server_architecture: Windows NT 10.0 AMD64
httpd_software: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.2.31
php_version: 7.2.31 64bit
php_sapi: apache2handler
max_input_variables: 100000
time_limit: 3600
memory_limit: 512M
max_input_time: 3600
upload_max_filesize: 250M
php_post_max_size: 250M
curl_version: 7.67.0 OpenSSL/1.1.1g
suhosin: false
imagick_availability: false
pretty_permalinks: true
htaccess_extra_rules: false

### wp-database ###

extension: mysqli
server_version: 10.4.11-MariaDB
client_version: mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579 $

### wp-constants ###

WP_HOME: undefined
WP_SITEURL: undefined
WP_CONTENT_DIR: F:\xampp\htdocs\pprf-demo/wp-content
WP_PLUGIN_DIR: F:\xampp\htdocs\pprf-demo/wp-content/plugins
WP_MAX_MEMORY_LIMIT: 512M
WP_DEBUG: true
WP_DEBUG_DISPLAY: false
WP_DEBUG_LOG: true
SCRIPT_DEBUG: true
WP_CACHE: false
CONCATENATE_SCRIPTS: undefined
COMPRESS_SCRIPTS: undefined
COMPRESS_CSS: undefined
WP_LOCAL_DEV: undefined
DB_CHARSET: utf8mb4
DB_COLLATE: undefined

### wp-filesystem ###

wordpress: writable
wp-content: writable
uploads: writable
plugins: writable
themes: writable

### pods ###

pods-server-software: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.2.31
pods-user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36
pods-session-save-path: F:\xampp\tmp
pods-session-save-path-exists: Yes
pods-session-save-path-writable: Yes
pods-session-max-lifetime: 1440
pods-opcode-cache-apc: No
pods-opcode-cache-memcached: No
pods-opcode-cache-opcache: No
pods-opcode-cache-redis: No
pods-object-cache-apc: No
pods-object-cache-apcu: No
pods-object-cache-memcache: No
pods-object-cache-memcached: No
pods-object-cache-redis: No
pods-memory-current-usage: 41.624M
pods-memory-current-usage-real: 8.000M
pods-network-wide: No
pods-install-location: F:\xampp\htdocs\pprf-demo\wp-content\plugins\pods/
pods-developer: No
pods-tableless-mode: No
pods-light-mode: No
pods-strict: Yes
pods-allow-deprecated: No
pods-api-cache: Yes
pods-shortcode-allow-evaluate-tags: No

`

</details>

<details>
<summary>Pods Package Export</summary>

{"meta":{"version":"2.8.0-b-1","build":1613152311},"pods":{"member":{"object_type":"pod","storage_type":"post_type","name":"member","id":6,"label":"Members","description":"","label_singular":"Member","public":"1","show_ui":"1","type":"pod","storage":"table","pod_index":"name","_locale":"user","podType":{"name":"pod","label":"Advanced Content Type"},"storageType":{"name":"table","label":"Table"},"show_in_menu":"1","menu_position":"1888"}}}
</details>

### PR DESCRIPTION
**Pull request by unknownnf**
## Description

After commit beea5e6ad the code was creating an array like `['name'=>$field]` where `$field` was an object, causing __toString to be called and then pods_v to fail in finding the right values.

## Related GitHub issue(s)

Fixes #5946 

## Testing instructions

Create a pod, normal or advanced, or use my exported Pods package below.
On the page template, add this code: ```$pod = pods( 'member' ); echo $pod->form( );```

Use the following export and add some fields to it

```
{"meta":{"version":"2.8.0-b-1","build":1613152311},"pods":{"member":{"object_type":"pod","storage_type":"post_type","name":"member","id":6,"label":"Members","description":"","label_singular":"Member","public":"1","show_ui":"1","type":"pod","storage":"table","pod_index":"name","_locale":"user","podType":{"name":"pod","label":"Advanced Content Type"},"storageType":{"name":"table","label":"Table"},"show_in_menu":"1","menu_position":"1888"}}}
```

## Screenshots / screencast

https://i.ibb.co/6szyqgS/Screenshot-from-2021-06-16-19-18-26.png

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- [x] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

File: classes/Pods.php [hunk 1]
```diff
@@ -3736,7 +3736,7 @@ public function form( $params = null, $label = null, $thank_you = null ) {
 				'name' => $name,
 			];
 
-			if ( ! is_array( $field ) ) {
+			if ( ! is_array( $field ) && ! is_object( $field ) ) {
```
Comment (sc0ttkclark) [inline classes/Pods.php:3739]:
```suggestion
			if ( is_string( $field ) ) {
```

Comment (sc0ttkclark) [reply classes/Pods.php:3739]: This might be better in hindsight, thoughts? @unknownnf

Comment (unknownnf) [reply classes/Pods.php]: I've updated the commit, checked with everything too. The only cases where this would fail would be empty arrays I guess? But that should not be the case at this point.

**Review by sc0ttkclark — APPROVED** [review]
