### PR TITLE
Fix post type archive visibility

### LINKED ISSUE #5304: Bug: Archive Remains when Enable Archive is unchecked
## Issue Overview
After checking 'Enable Archive Page' (and providing an Archive Page Slug Override) in Edit Pods, Advanced Options, archive is enabled. Unchecking (to disable the archive), the archive remains 'enabled' in WordPress, even though Pods Admin shows the archive is not 'Enabled'.

## Expected Behavior
Disabling Archive should NOT leave it 'enabled' (has_archive should still represent as 'false' and there should not be a rewrite rule that points to the archives.

## Current Behavior
Enabling Archives, enables archive. Unchecking 'Enable Archive Page' leaves the archive enabled.

Archive is Unchecked
screenshot 2019-02-26 08 23 59

View Tests (View Archive is still available
screenshot 2019-02-26 08 24 19

Archive Front-end Post Type Archives: Tests is still visible
screenshot 2019-02-26 08 24 34

## Steps to Reproduce (for bugs)

1. Create a Custom Post Type
2. Enable Archive under Advanced Options, 'Enable Archive Page'. Save and verify it works.
3. Edit pod, and Uncheck 'Enable Archive Page'. Save and Pods Settings, Clear Cache (just in case)
4. Visit Custom Post Type and see that View Archives is still available.

Current Pods Version 2.7.12

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #5304

## PR checklist

- [x] I have tested my own code to confirm it works as I intended.
- [x] My code follows the [WordPress Coding Standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/).
- [x] My code follows the [WordPress Inline Documentation Standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/).
- ~~My code includes automated tests for PHP and/or JS (if applicable).~~

### CODE REVIEW

**Review by sc0ttkclark — DISMISSED** [review]

File: classes/PodsInit.php [hunk 1]
```diff
@@ -1012,7 +1012,7 @@ public function setup_content_types( $force = false ) {
 					'supports'            => $cpt_supports,
 					// 'register_meta_box_cb' => array($this, 'manage_meta_box'),
 					// 'permalink_epmask' => EP_PERMALINK,
-					'has_archive'         => pods_v( 'has_archive_slug', $post_type, (boolean) pods_v( 'has_archive', $post_type, false ), true ),
+					'has_archive'         => ( pods_v( 'has_archive', $post_type, false ) ) ? pods_v( 'has_archive_slug', $post_type, true, true ) : false,
```
Comment (sc0ttkclark) [inline classes/PodsInit.php:1015]:
```suggestion
					'has_archive'         => ( (boolean) pods_v( 'has_archive', $post_type, false ) ) ? pods_v( 'has_archive_slug', $post_type, true, true ) : false,
```

**Review by sc0ttkclark — APPROVED** [review]

**Comment by sc0ttkclark** [comment]
Merged into release/2.7.29 for release
