### PR TITLE
Custom no access message for templates

### LINKED ISSUE #5875: hide text "You do not have access to view this content."
## Issue Overview

The restricted content feature is working in the template, but then it is displaying text "You do not have access to view this content." We would prefer to have nothing display instead of what looks like an error message. It is hiding the pods content which we wanted - but the way it is handled looks like an error.

## Expected Behavior

We would prefer that the text "You do not have access to view this content." not appear for users not authorized to view. It would be better if that text area was empty.

Is there a control that we have not been able to find by which we can configure whether or not that auth message shows, and if we want it to show, allow us to enter text we prefer to be displayed?

 

## Steps to Reproduce (for bugs)

1. Edit POD template
2. Restrict Access either by "Show to Admins Only?" or by "Restrict access by Capability?"
3. View live page - where the POD content would normally display shows the text "You do not have access to view this content." to viewers who lack authorization.

## Possible Solution

Is there Custom CSS we could add which would hide the text "You do not have access to view this content" using the WP Appearance tool?

## WordPress Environment

WordPress 5.5.2 running Property Rental WordPress Theme theme.

<details>
```
Copy and paste your System Details from **Pods Admin > Settings > Debug Information** in WordPress admin here.
```
</details>

Debug Information
WordPress Version: 5.5.2

PHP Version: 7.3.12

MySQL Version: 5.6.32

Server Software: Apache

Your User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

Session Save Path:

Session Save Path Exists: No

Session Save Path Writeable: No

Session Max Lifetime: 1440

Opcode Cache:

Apc: Yes
Memcached: No
OPcache: Yes
Redis: No
Object Cache:

APC: Yes
APCu: Yes
Memcache: Yes
Memcached: No
Redis: No
WPDB Prefix: wp_9t3khd9gqx_

WP Multisite Mode: No

WP Memory Limit: 40M

Current Memory Usage: 11.071M

Current Memory Usage (real): 4.000M

Pods Network-Wide Activated: No

Pods Install Location: /var/www/wp-content/plugins/pods/

Pods Tableless Mode Activated: No

Pods Light Mode Activated: No

Currently Active Theme: Property Rental WordPress Theme

Currently Active Plugins:

API KEY for Google Maps: 1.2.0
Ninja Forms: 3.4.30
Ninja Forms - Addon Manager: 3.0.13
Pods - Custom Content Types and Fields: 2.7.23
Show-Hide/Collapse-Expand: 1.2.4
SiteOrigin CSS: 1.2.11
Smart Slider 3: 3.4.1.11
UpdraftPlus - Backup/Restore: 1.16.34
Widget Importer & Exporter: 1.6
WordPress Importer: 0.7
WP Google Maps: 8.0.26
WP Google Maps - Pro Add-on: 7.11.69
Yoast Duplicate Post: 3.2.6

## Pods Package Export (helpful!)

```
Copy and Paste the JSON Export from **Pods Admin, Migrate: Packages, Export** in WordPress admin here
```

### PR DESCRIPTION
**Pull request by JoryHogeveen**
Fixes #5875 

## Description

This PR adds 2 new options to Pods Templates:
- Boolean: Show no-access message (default: true)
- Wysiwyg: No access message (overwrites default)

## PR Checklist

- [x] My code is tested.
- [x] My code follows the WordPress code style.
- [x] My code follows has proper inline documentation.
- [ ] My code includes automated tests for PHP and/or JS (if applicable).

### CODE REVIEW

File: components/Templates/Templates.php [hunk 1]
```diff
@@ -395,6 +395,23 @@ public function add_meta_boxes() {
 					'restrict_capability' => true,
 				),
 			),
+			array(
```
Comment (tr1b0t) [inline components/Templates/Templates.php:398]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 4bcd1674b33f5e353e0724ee4d2728ed</sub>

File: components/Templates/Templates.php [hunk 2]
```diff
@@ -395,6 +395,23 @@ public function add_meta_boxes() {
...
+				'name'       => 'show_restrict_message',
+				'label'      => __( 'Show no access message?', 'pods' ),
+				'default'    => 1,
+				'type'       => 'boolean',
+				'dependency' => true,
+			),
+			array(
```
Comment (tr1b0t) [inline components/Templates/Templates.php:405]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 556194f118e48b5841b50130997da2d3</sub>

File: components/Templates/Templates.php [hunk 3]
```diff
@@ -395,6 +395,23 @@ public function add_meta_boxes() {
...
+				'name'                  => 'restrict_message',
+				'label'                 => __( 'No access message', 'pods' ),
+				'type'                  => 'wysiwyg',
+				'default'               => __( 'You do not have access to view this content.', 'pods' ),
+				'wysiwyg_editor_height' => 200,
+				'depends-on'            => array(
```
Comment (tr1b0t) [inline components/Templates/Templates.php:411]: :no_entry_sign: Short array syntax must be used to define arrays

<sub>hash: 814b59c3b7984cfcac741f040cd3ec63</sub>

File: components/Templates/Templates.php [hunk 4]
```diff
@@ -395,6 +395,23 @@ public function add_meta_boxes() {
...
+					'show_restrict_message' => true,
+				),
+			)
```
Comment (tr1b0t) [inline components/Templates/Templates.php:414]: * :no_entry_sign: Comma required after last value in array declaration
* :no_entry_sign: Each array item in a multi-line array declaration must end in a comma

<sub>hash: 5a3482489271bae52396a1592e6a6371</sub>

**Review by tr1b0t — COMMENTED** [review]
:no_entry_sign: 5 error(s)

**Comment by JoryHogeveen** [comment]
@sc0ttkclark 

This PR already works but the boolean field types aren't bug free when the `default` is set to `true`.
Since `_pods_template` isn't a registered Pod type it won't load the Pod object and thus the field values are fetched using `get_post_meta`. This returns false for a boolean if unchecked and in turn the Pods templates always revert to the default value.

For this reason the new `show_restrict_message` options always shows as checked.
If I understood you correctly this is fixed in 2.8.

File: components/Templates/Templates.php [hunk 5]
```diff
@@ -509,12 +526,19 @@ public static function template( $template_name, $code = null, $obj = null, $dep
...
-				$permission = pods_permission( $template['options'] );
+				$options = pods_v( 'options', $template );
+
+				$permission = pods_permission( $options );
 
 				$permission = (boolean) apply_filters( 'pods_templates_permission', $permission, $code, $template, $obj );
 
 				if ( ! $permission ) {
-					return apply_filters( 'pods_templates_permission_denied', __( 'You do not have access to view this content.', 'pods' ), $code, $template, $obj );
+					if ( pods_v( 'show_restrict_message', $options, true ) ) {
```
Comment (sc0ttkclark) [inline components/Templates/Templates.php:536]:
```suggestion
					if ( 1 === (int) pods_v( 'show_restrict_message', $options, 1 ) ) {
```

Comment (JoryHogeveen) [reply components/Templates/Templates.php:536]: Why compare as int?

Comment (sc0ttkclark) [reply components/Templates/Templates.php:536]: Since it could come as a '0' or string

**Review by sc0ttkclark — DISMISSED** [review]

File: components/Templates/Templates.php [hunk 6]
```diff
@@ -509,12 +526,19 @@ public static function template( $template_name, $code = null, $obj = null, $dep
...
+				$options = pods_v( 'options', $template );
+
+				$permission = pods_permission( $options );
 
 				$permission = (boolean) apply_filters( 'pods_templates_permission', $permission, $code, $template, $obj );
 
 				if ( ! $permission ) {
-					return apply_filters( 'pods_templates_permission_denied', __( 'You do not have access to view this content.', 'pods' ), $code, $template, $obj );
+					if ( 1 === (int) pods_v( 'show_restrict_message', $options, 1 ) ) {
+						$message = pods_v( 'restrict_message', $options, __( 'You do not have access to view this content.', 'pods' ) );
```
Comment (sc0ttkclark) [inline components/Templates/Templates.php:537]:
```suggestion
						$message = pods_v( 'restrict_message', $options, __( 'You do not have access to view this content.', 'pods' ), true );
```

Comment (sc0ttkclark) [reply components/Templates/Templates.php:537]: Ensure that even if it's set and empty, we use the default

**Review by sc0ttkclark — APPROVED** [review]

**Comment by sc0ttkclark** [comment]
Merged into release/2.7.25
